// Generated by gencpp from file swarm_msgs/FisheyeFrameDescriptor.msg
// DO NOT EDIT!


#ifndef SWARM_MSGS_MESSAGE_FISHEYEFRAMEDESCRIPTOR_H
#define SWARM_MSGS_MESSAGE_FISHEYEFRAMEDESCRIPTOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>
#include <swarm_msgs/ImageDescriptor.h>

namespace swarm_msgs
{
template <class ContainerAllocator>
struct FisheyeFrameDescriptor_
{
  typedef FisheyeFrameDescriptor_<ContainerAllocator> Type;

  FisheyeFrameDescriptor_()
    : header()
    , prevent_adding_db(false)
    , landmark_num(0)
    , drone_id(0)
    , msg_id(0)
    , pose_drone()
    , images()  {
    }
  FisheyeFrameDescriptor_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , prevent_adding_db(false)
    , landmark_num(0)
    , drone_id(0)
    , msg_id(0)
    , pose_drone(_alloc)
    , images(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _prevent_adding_db_type;
  _prevent_adding_db_type prevent_adding_db;

   typedef int32_t _landmark_num_type;
  _landmark_num_type landmark_num;

   typedef int32_t _drone_id_type;
  _drone_id_type drone_id;

   typedef int64_t _msg_id_type;
  _msg_id_type msg_id;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_drone_type;
  _pose_drone_type pose_drone;

   typedef std::vector< ::swarm_msgs::ImageDescriptor_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::swarm_msgs::ImageDescriptor_<ContainerAllocator> >> _images_type;
  _images_type images;





  typedef boost::shared_ptr< ::swarm_msgs::FisheyeFrameDescriptor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_msgs::FisheyeFrameDescriptor_<ContainerAllocator> const> ConstPtr;

}; // struct FisheyeFrameDescriptor_

typedef ::swarm_msgs::FisheyeFrameDescriptor_<std::allocator<void> > FisheyeFrameDescriptor;

typedef boost::shared_ptr< ::swarm_msgs::FisheyeFrameDescriptor > FisheyeFrameDescriptorPtr;
typedef boost::shared_ptr< ::swarm_msgs::FisheyeFrameDescriptor const> FisheyeFrameDescriptorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_msgs::FisheyeFrameDescriptor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_msgs::FisheyeFrameDescriptor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm_msgs::FisheyeFrameDescriptor_<ContainerAllocator1> & lhs, const ::swarm_msgs::FisheyeFrameDescriptor_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.prevent_adding_db == rhs.prevent_adding_db &&
    lhs.landmark_num == rhs.landmark_num &&
    lhs.drone_id == rhs.drone_id &&
    lhs.msg_id == rhs.msg_id &&
    lhs.pose_drone == rhs.pose_drone &&
    lhs.images == rhs.images;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm_msgs::FisheyeFrameDescriptor_<ContainerAllocator1> & lhs, const ::swarm_msgs::FisheyeFrameDescriptor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarm_msgs::FisheyeFrameDescriptor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_msgs::FisheyeFrameDescriptor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_msgs::FisheyeFrameDescriptor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_msgs::FisheyeFrameDescriptor_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_msgs::FisheyeFrameDescriptor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_msgs::FisheyeFrameDescriptor_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_msgs::FisheyeFrameDescriptor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "06020b9f79d2ac92cae2a950ef662e84";
  }

  static const char* value(const ::swarm_msgs::FisheyeFrameDescriptor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x06020b9f79d2ac92ULL;
  static const uint64_t static_value2 = 0xcae2a950ef662e84ULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_msgs::FisheyeFrameDescriptor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_msgs/FisheyeFrameDescriptor";
  }

  static const char* value(const ::swarm_msgs::FisheyeFrameDescriptor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_msgs::FisheyeFrameDescriptor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"bool prevent_adding_db\n"
"int32 landmark_num\n"
"int32 drone_id\n"
"int64 msg_id\n"
"geometry_msgs/Pose pose_drone\n"
"ImageDescriptor[] images\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: swarm_msgs/ImageDescriptor\n"
"Header header\n"
"int32 drone_id\n"
"\n"
"float32[] feature_descriptor\n"
"\n"
"geometry_msgs/Pose pose_drone\n"
"geometry_msgs/Pose camera_extrinsic\n"
"\n"
"float32[] image_desc\n"
"int32 image_width\n"
"int32 image_height\n"
"uint8[] image\n"
"\n"
"geometry_msgs/Point32[] landmarks_2d_norm\n"
"geometry_msgs/Point32[] landmarks_2d\n"
"geometry_msgs/Point32[] landmarks_3d\n"
"uint8[] landmarks_flag\n"
"bool prevent_adding_db\n"
"\n"
"int32 direction\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::swarm_msgs::FisheyeFrameDescriptor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_msgs::FisheyeFrameDescriptor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.prevent_adding_db);
      stream.next(m.landmark_num);
      stream.next(m.drone_id);
      stream.next(m.msg_id);
      stream.next(m.pose_drone);
      stream.next(m.images);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FisheyeFrameDescriptor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_msgs::FisheyeFrameDescriptor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_msgs::FisheyeFrameDescriptor_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "prevent_adding_db: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.prevent_adding_db);
    s << indent << "landmark_num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.landmark_num);
    s << indent << "drone_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.drone_id);
    s << indent << "msg_id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.msg_id);
    s << indent << "pose_drone: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose_drone);
    s << indent << "images[]" << std::endl;
    for (size_t i = 0; i < v.images.size(); ++i)
    {
      s << indent << "  images[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::swarm_msgs::ImageDescriptor_<ContainerAllocator> >::stream(s, indent + "    ", v.images[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_MSGS_MESSAGE_FISHEYEFRAMEDESCRIPTOR_H
