// Generated by gencpp from file swarm_msgs/ImageDescriptor.msg
// DO NOT EDIT!


#ifndef SWARM_MSGS_MESSAGE_IMAGEDESCRIPTOR_H
#define SWARM_MSGS_MESSAGE_IMAGEDESCRIPTOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Point32.h>
#include <geometry_msgs/Point32.h>
#include <geometry_msgs/Point32.h>

namespace swarm_msgs
{
template <class ContainerAllocator>
struct ImageDescriptor_
{
  typedef ImageDescriptor_<ContainerAllocator> Type;

  ImageDescriptor_()
    : header()
    , drone_id(0)
    , feature_descriptor()
    , pose_drone()
    , camera_extrinsic()
    , image_desc()
    , image_width(0)
    , image_height(0)
    , image()
    , landmarks_2d_norm()
    , landmarks_2d()
    , landmarks_3d()
    , landmarks_flag()
    , prevent_adding_db(false)
    , direction(0)  {
    }
  ImageDescriptor_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , drone_id(0)
    , feature_descriptor(_alloc)
    , pose_drone(_alloc)
    , camera_extrinsic(_alloc)
    , image_desc(_alloc)
    , image_width(0)
    , image_height(0)
    , image(_alloc)
    , landmarks_2d_norm(_alloc)
    , landmarks_2d(_alloc)
    , landmarks_3d(_alloc)
    , landmarks_flag(_alloc)
    , prevent_adding_db(false)
    , direction(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _drone_id_type;
  _drone_id_type drone_id;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _feature_descriptor_type;
  _feature_descriptor_type feature_descriptor;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_drone_type;
  _pose_drone_type pose_drone;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _camera_extrinsic_type;
  _camera_extrinsic_type camera_extrinsic;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _image_desc_type;
  _image_desc_type image_desc;

   typedef int32_t _image_width_type;
  _image_width_type image_width;

   typedef int32_t _image_height_type;
  _image_height_type image_height;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _image_type;
  _image_type image;

   typedef std::vector< ::geometry_msgs::Point32_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point32_<ContainerAllocator> >> _landmarks_2d_norm_type;
  _landmarks_2d_norm_type landmarks_2d_norm;

   typedef std::vector< ::geometry_msgs::Point32_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point32_<ContainerAllocator> >> _landmarks_2d_type;
  _landmarks_2d_type landmarks_2d;

   typedef std::vector< ::geometry_msgs::Point32_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point32_<ContainerAllocator> >> _landmarks_3d_type;
  _landmarks_3d_type landmarks_3d;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _landmarks_flag_type;
  _landmarks_flag_type landmarks_flag;

   typedef uint8_t _prevent_adding_db_type;
  _prevent_adding_db_type prevent_adding_db;

   typedef int32_t _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::swarm_msgs::ImageDescriptor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_msgs::ImageDescriptor_<ContainerAllocator> const> ConstPtr;

}; // struct ImageDescriptor_

typedef ::swarm_msgs::ImageDescriptor_<std::allocator<void> > ImageDescriptor;

typedef boost::shared_ptr< ::swarm_msgs::ImageDescriptor > ImageDescriptorPtr;
typedef boost::shared_ptr< ::swarm_msgs::ImageDescriptor const> ImageDescriptorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_msgs::ImageDescriptor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_msgs::ImageDescriptor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm_msgs::ImageDescriptor_<ContainerAllocator1> & lhs, const ::swarm_msgs::ImageDescriptor_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.drone_id == rhs.drone_id &&
    lhs.feature_descriptor == rhs.feature_descriptor &&
    lhs.pose_drone == rhs.pose_drone &&
    lhs.camera_extrinsic == rhs.camera_extrinsic &&
    lhs.image_desc == rhs.image_desc &&
    lhs.image_width == rhs.image_width &&
    lhs.image_height == rhs.image_height &&
    lhs.image == rhs.image &&
    lhs.landmarks_2d_norm == rhs.landmarks_2d_norm &&
    lhs.landmarks_2d == rhs.landmarks_2d &&
    lhs.landmarks_3d == rhs.landmarks_3d &&
    lhs.landmarks_flag == rhs.landmarks_flag &&
    lhs.prevent_adding_db == rhs.prevent_adding_db &&
    lhs.direction == rhs.direction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm_msgs::ImageDescriptor_<ContainerAllocator1> & lhs, const ::swarm_msgs::ImageDescriptor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarm_msgs::ImageDescriptor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_msgs::ImageDescriptor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_msgs::ImageDescriptor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_msgs::ImageDescriptor_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_msgs::ImageDescriptor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_msgs::ImageDescriptor_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_msgs::ImageDescriptor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f5e8e454632afe4a9ed9bcee95f3cff";
  }

  static const char* value(const ::swarm_msgs::ImageDescriptor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f5e8e454632afe4ULL;
  static const uint64_t static_value2 = 0xa9ed9bcee95f3cffULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_msgs::ImageDescriptor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_msgs/ImageDescriptor";
  }

  static const char* value(const ::swarm_msgs::ImageDescriptor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_msgs::ImageDescriptor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 drone_id\n"
"\n"
"float32[] feature_descriptor\n"
"\n"
"geometry_msgs/Pose pose_drone\n"
"geometry_msgs/Pose camera_extrinsic\n"
"\n"
"float32[] image_desc\n"
"int32 image_width\n"
"int32 image_height\n"
"uint8[] image\n"
"\n"
"geometry_msgs/Point32[] landmarks_2d_norm\n"
"geometry_msgs/Point32[] landmarks_2d\n"
"geometry_msgs/Point32[] landmarks_3d\n"
"uint8[] landmarks_flag\n"
"bool prevent_adding_db\n"
"\n"
"int32 direction\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::swarm_msgs::ImageDescriptor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_msgs::ImageDescriptor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.drone_id);
      stream.next(m.feature_descriptor);
      stream.next(m.pose_drone);
      stream.next(m.camera_extrinsic);
      stream.next(m.image_desc);
      stream.next(m.image_width);
      stream.next(m.image_height);
      stream.next(m.image);
      stream.next(m.landmarks_2d_norm);
      stream.next(m.landmarks_2d);
      stream.next(m.landmarks_3d);
      stream.next(m.landmarks_flag);
      stream.next(m.prevent_adding_db);
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageDescriptor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_msgs::ImageDescriptor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_msgs::ImageDescriptor_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "drone_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.drone_id);
    s << indent << "feature_descriptor[]" << std::endl;
    for (size_t i = 0; i < v.feature_descriptor.size(); ++i)
    {
      s << indent << "  feature_descriptor[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.feature_descriptor[i]);
    }
    s << indent << "pose_drone: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose_drone);
    s << indent << "camera_extrinsic: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.camera_extrinsic);
    s << indent << "image_desc[]" << std::endl;
    for (size_t i = 0; i < v.image_desc.size(); ++i)
    {
      s << indent << "  image_desc[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.image_desc[i]);
    }
    s << indent << "image_width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.image_width);
    s << indent << "image_height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.image_height);
    s << indent << "image[]" << std::endl;
    for (size_t i = 0; i < v.image.size(); ++i)
    {
      s << indent << "  image[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.image[i]);
    }
    s << indent << "landmarks_2d_norm[]" << std::endl;
    for (size_t i = 0; i < v.landmarks_2d_norm.size(); ++i)
    {
      s << indent << "  landmarks_2d_norm[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "    ", v.landmarks_2d_norm[i]);
    }
    s << indent << "landmarks_2d[]" << std::endl;
    for (size_t i = 0; i < v.landmarks_2d.size(); ++i)
    {
      s << indent << "  landmarks_2d[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "    ", v.landmarks_2d[i]);
    }
    s << indent << "landmarks_3d[]" << std::endl;
    for (size_t i = 0; i < v.landmarks_3d.size(); ++i)
    {
      s << indent << "  landmarks_3d[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "    ", v.landmarks_3d[i]);
    }
    s << indent << "landmarks_flag[]" << std::endl;
    for (size_t i = 0; i < v.landmarks_flag.size(); ++i)
    {
      s << indent << "  landmarks_flag[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.landmarks_flag[i]);
    }
    s << indent << "prevent_adding_db: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.prevent_adding_db);
    s << indent << "direction: ";
    Printer<int32_t>::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_MSGS_MESSAGE_IMAGEDESCRIPTOR_H
