// Generated by gencpp from file swarm_msgs/LoopEdge.msg
// DO NOT EDIT!


#ifndef SWARM_MSGS_MESSAGE_LOOPEDGE_H
#define SWARM_MSGS_MESSAGE_LOOPEDGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace swarm_msgs
{
template <class ContainerAllocator>
struct LoopEdge_
{
  typedef LoopEdge_<ContainerAllocator> Type;

  LoopEdge_()
    : ts_a()
    , ts_b()
    , drone_id_a(0)
    , drone_id_b(0)
    , keyframe_id_a(0)
    , keyframe_id_b(0)
    , relative_pose()
    , self_pose_a()
    , self_pose_b()
    , pos_cov()
    , ang_cov()
    , pnp_inlier_num(0)
    , is_4dof(false)
    , id(0)  {
    }
  LoopEdge_(const ContainerAllocator& _alloc)
    : ts_a()
    , ts_b()
    , drone_id_a(0)
    , drone_id_b(0)
    , keyframe_id_a(0)
    , keyframe_id_b(0)
    , relative_pose(_alloc)
    , self_pose_a(_alloc)
    , self_pose_b(_alloc)
    , pos_cov(_alloc)
    , ang_cov(_alloc)
    , pnp_inlier_num(0)
    , is_4dof(false)
    , id(0)  {
  (void)_alloc;
    }



   typedef ros::Time _ts_a_type;
  _ts_a_type ts_a;

   typedef ros::Time _ts_b_type;
  _ts_b_type ts_b;

   typedef uint64_t _drone_id_a_type;
  _drone_id_a_type drone_id_a;

   typedef uint64_t _drone_id_b_type;
  _drone_id_b_type drone_id_b;

   typedef uint64_t _keyframe_id_a_type;
  _keyframe_id_a_type keyframe_id_a;

   typedef uint64_t _keyframe_id_b_type;
  _keyframe_id_b_type keyframe_id_b;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _relative_pose_type;
  _relative_pose_type relative_pose;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _self_pose_a_type;
  _self_pose_a_type self_pose_a;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _self_pose_b_type;
  _self_pose_b_type self_pose_b;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _pos_cov_type;
  _pos_cov_type pos_cov;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _ang_cov_type;
  _ang_cov_type ang_cov;

   typedef int32_t _pnp_inlier_num_type;
  _pnp_inlier_num_type pnp_inlier_num;

   typedef uint8_t _is_4dof_type;
  _is_4dof_type is_4dof;

   typedef uint64_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::swarm_msgs::LoopEdge_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_msgs::LoopEdge_<ContainerAllocator> const> ConstPtr;

}; // struct LoopEdge_

typedef ::swarm_msgs::LoopEdge_<std::allocator<void> > LoopEdge;

typedef boost::shared_ptr< ::swarm_msgs::LoopEdge > LoopEdgePtr;
typedef boost::shared_ptr< ::swarm_msgs::LoopEdge const> LoopEdgeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_msgs::LoopEdge_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_msgs::LoopEdge_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm_msgs::LoopEdge_<ContainerAllocator1> & lhs, const ::swarm_msgs::LoopEdge_<ContainerAllocator2> & rhs)
{
  return lhs.ts_a == rhs.ts_a &&
    lhs.ts_b == rhs.ts_b &&
    lhs.drone_id_a == rhs.drone_id_a &&
    lhs.drone_id_b == rhs.drone_id_b &&
    lhs.keyframe_id_a == rhs.keyframe_id_a &&
    lhs.keyframe_id_b == rhs.keyframe_id_b &&
    lhs.relative_pose == rhs.relative_pose &&
    lhs.self_pose_a == rhs.self_pose_a &&
    lhs.self_pose_b == rhs.self_pose_b &&
    lhs.pos_cov == rhs.pos_cov &&
    lhs.ang_cov == rhs.ang_cov &&
    lhs.pnp_inlier_num == rhs.pnp_inlier_num &&
    lhs.is_4dof == rhs.is_4dof &&
    lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm_msgs::LoopEdge_<ContainerAllocator1> & lhs, const ::swarm_msgs::LoopEdge_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarm_msgs::LoopEdge_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_msgs::LoopEdge_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_msgs::LoopEdge_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_msgs::LoopEdge_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_msgs::LoopEdge_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_msgs::LoopEdge_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_msgs::LoopEdge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad50fe35eb11e19dfe778de2e9e9026b";
  }

  static const char* value(const ::swarm_msgs::LoopEdge_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad50fe35eb11e19dULL;
  static const uint64_t static_value2 = 0xfe778de2e9e9026bULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_msgs::LoopEdge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_msgs/LoopEdge";
  }

  static const char* value(const ::swarm_msgs::LoopEdge_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_msgs::LoopEdge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time ts_a\n"
"time ts_b\n"
"uint64 drone_id_a\n"
"uint64 drone_id_b\n"
"uint64 keyframe_id_a\n"
"uint64 keyframe_id_b\n"
"geometry_msgs/Pose relative_pose\n"
"\n"
"geometry_msgs/Pose self_pose_a\n"
"geometry_msgs/Pose self_pose_b\n"
"\n"
"geometry_msgs/Point pos_cov\n"
"geometry_msgs/Point ang_cov\n"
"\n"
"#Details for loop\n"
"int32 pnp_inlier_num\n"
"bool is_4dof\n"
"uint64 id\n"
"\n"
"#geometry_msgs/Point[] point_cloud_b\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::swarm_msgs::LoopEdge_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_msgs::LoopEdge_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ts_a);
      stream.next(m.ts_b);
      stream.next(m.drone_id_a);
      stream.next(m.drone_id_b);
      stream.next(m.keyframe_id_a);
      stream.next(m.keyframe_id_b);
      stream.next(m.relative_pose);
      stream.next(m.self_pose_a);
      stream.next(m.self_pose_b);
      stream.next(m.pos_cov);
      stream.next(m.ang_cov);
      stream.next(m.pnp_inlier_num);
      stream.next(m.is_4dof);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LoopEdge_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_msgs::LoopEdge_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_msgs::LoopEdge_<ContainerAllocator>& v)
  {
    s << indent << "ts_a: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.ts_a);
    s << indent << "ts_b: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.ts_b);
    s << indent << "drone_id_a: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.drone_id_a);
    s << indent << "drone_id_b: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.drone_id_b);
    s << indent << "keyframe_id_a: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.keyframe_id_a);
    s << indent << "keyframe_id_b: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.keyframe_id_b);
    s << indent << "relative_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.relative_pose);
    s << indent << "self_pose_a: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.self_pose_a);
    s << indent << "self_pose_b: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.self_pose_b);
    s << indent << "pos_cov: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.pos_cov);
    s << indent << "ang_cov: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.ang_cov);
    s << indent << "pnp_inlier_num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pnp_inlier_num);
    s << indent << "is_4dof: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_4dof);
    s << indent << "id: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_MSGS_MESSAGE_LOOPEDGE_H
