// Generated by gencpp from file swarm_msgs/LoopEdges.msg
// DO NOT EDIT!


#ifndef SWARM_MSGS_MESSAGE_LOOPEDGES_H
#define SWARM_MSGS_MESSAGE_LOOPEDGES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <swarm_msgs/LoopEdge.h>

namespace swarm_msgs
{
template <class ContainerAllocator>
struct LoopEdges_
{
  typedef LoopEdges_<ContainerAllocator> Type;

  LoopEdges_()
    : header()
    , loops()  {
    }
  LoopEdges_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , loops(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::swarm_msgs::LoopEdge_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::swarm_msgs::LoopEdge_<ContainerAllocator> >> _loops_type;
  _loops_type loops;





  typedef boost::shared_ptr< ::swarm_msgs::LoopEdges_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_msgs::LoopEdges_<ContainerAllocator> const> ConstPtr;

}; // struct LoopEdges_

typedef ::swarm_msgs::LoopEdges_<std::allocator<void> > LoopEdges;

typedef boost::shared_ptr< ::swarm_msgs::LoopEdges > LoopEdgesPtr;
typedef boost::shared_ptr< ::swarm_msgs::LoopEdges const> LoopEdgesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_msgs::LoopEdges_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_msgs::LoopEdges_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm_msgs::LoopEdges_<ContainerAllocator1> & lhs, const ::swarm_msgs::LoopEdges_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.loops == rhs.loops;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm_msgs::LoopEdges_<ContainerAllocator1> & lhs, const ::swarm_msgs::LoopEdges_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarm_msgs::LoopEdges_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_msgs::LoopEdges_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_msgs::LoopEdges_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_msgs::LoopEdges_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_msgs::LoopEdges_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_msgs::LoopEdges_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_msgs::LoopEdges_<ContainerAllocator> >
{
  static const char* value()
  {
    return "90a7ebaed3f91cb5af316ff75b2d20ac";
  }

  static const char* value(const ::swarm_msgs::LoopEdges_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x90a7ebaed3f91cb5ULL;
  static const uint64_t static_value2 = 0xaf316ff75b2d20acULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_msgs::LoopEdges_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_msgs/LoopEdges";
  }

  static const char* value(const ::swarm_msgs::LoopEdges_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_msgs::LoopEdges_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"LoopEdge[] loops\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: swarm_msgs/LoopEdge\n"
"time ts_a\n"
"time ts_b\n"
"uint64 drone_id_a\n"
"uint64 drone_id_b\n"
"uint64 keyframe_id_a\n"
"uint64 keyframe_id_b\n"
"geometry_msgs/Pose relative_pose\n"
"\n"
"geometry_msgs/Pose self_pose_a\n"
"geometry_msgs/Pose self_pose_b\n"
"\n"
"geometry_msgs/Point pos_cov\n"
"geometry_msgs/Point ang_cov\n"
"\n"
"#Details for loop\n"
"int32 pnp_inlier_num\n"
"bool is_4dof\n"
"uint64 id\n"
"\n"
"#geometry_msgs/Point[] point_cloud_b\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::swarm_msgs::LoopEdges_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_msgs::LoopEdges_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.loops);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LoopEdges_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_msgs::LoopEdges_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_msgs::LoopEdges_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "loops[]" << std::endl;
    for (size_t i = 0; i < v.loops.size(); ++i)
    {
      s << indent << "  loops[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::swarm_msgs::LoopEdge_<ContainerAllocator> >::stream(s, indent + "    ", v.loops[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_MSGS_MESSAGE_LOOPEDGES_H
