// Generated by gencpp from file swarm_msgs/node_frame.msg
// DO NOT EDIT!


#ifndef SWARM_MSGS_MESSAGE_NODE_FRAME_H
#define SWARM_MSGS_MESSAGE_NODE_FRAME_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Quaternion.h>
#include <swarm_msgs/node_detected_xyzyaw.h>
#include <swarm_msgs/node_detected.h>

namespace swarm_msgs
{
template <class ContainerAllocator>
struct node_frame_
{
  typedef node_frame_<ContainerAllocator> Type;

  node_frame_()
    : header()
    , drone_id(0)
    , keyframe_id(0)
    , position()
    , velocity()
    , yaw(0.0)
    , pitch(0.0)
    , roll(0.0)
    , quat()
    , vo_available(false)
    , dismap_ids()
    , dismap_dists()
    , detected_xyzyaws()
    , detected()  {
    }
  node_frame_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , drone_id(0)
    , keyframe_id(0)
    , position(_alloc)
    , velocity(_alloc)
    , yaw(0.0)
    , pitch(0.0)
    , roll(0.0)
    , quat(_alloc)
    , vo_available(false)
    , dismap_ids(_alloc)
    , dismap_dists(_alloc)
    , detected_xyzyaws(_alloc)
    , detected(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _drone_id_type;
  _drone_id_type drone_id;

   typedef uint64_t _keyframe_id_type;
  _keyframe_id_type keyframe_id;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _roll_type;
  _roll_type roll;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _quat_type;
  _quat_type quat;

   typedef uint8_t _vo_available_type;
  _vo_available_type vo_available;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _dismap_ids_type;
  _dismap_ids_type dismap_ids;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _dismap_dists_type;
  _dismap_dists_type dismap_dists;

   typedef std::vector< ::swarm_msgs::node_detected_xyzyaw_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::swarm_msgs::node_detected_xyzyaw_<ContainerAllocator> >> _detected_xyzyaws_type;
  _detected_xyzyaws_type detected_xyzyaws;

   typedef std::vector< ::swarm_msgs::node_detected_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::swarm_msgs::node_detected_<ContainerAllocator> >> _detected_type;
  _detected_type detected;





  typedef boost::shared_ptr< ::swarm_msgs::node_frame_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_msgs::node_frame_<ContainerAllocator> const> ConstPtr;

}; // struct node_frame_

typedef ::swarm_msgs::node_frame_<std::allocator<void> > node_frame;

typedef boost::shared_ptr< ::swarm_msgs::node_frame > node_framePtr;
typedef boost::shared_ptr< ::swarm_msgs::node_frame const> node_frameConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_msgs::node_frame_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_msgs::node_frame_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm_msgs::node_frame_<ContainerAllocator1> & lhs, const ::swarm_msgs::node_frame_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.drone_id == rhs.drone_id &&
    lhs.keyframe_id == rhs.keyframe_id &&
    lhs.position == rhs.position &&
    lhs.velocity == rhs.velocity &&
    lhs.yaw == rhs.yaw &&
    lhs.pitch == rhs.pitch &&
    lhs.roll == rhs.roll &&
    lhs.quat == rhs.quat &&
    lhs.vo_available == rhs.vo_available &&
    lhs.dismap_ids == rhs.dismap_ids &&
    lhs.dismap_dists == rhs.dismap_dists &&
    lhs.detected_xyzyaws == rhs.detected_xyzyaws &&
    lhs.detected == rhs.detected;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm_msgs::node_frame_<ContainerAllocator1> & lhs, const ::swarm_msgs::node_frame_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarm_msgs::node_frame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_msgs::node_frame_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_msgs::node_frame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_msgs::node_frame_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_msgs::node_frame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_msgs::node_frame_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_msgs::node_frame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8804cccece15c26162c55054a22f87c8";
  }

  static const char* value(const ::swarm_msgs::node_frame_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8804cccece15c261ULL;
  static const uint64_t static_value2 = 0x62c55054a22f87c8ULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_msgs::node_frame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_msgs/node_frame";
  }

  static const char* value(const ::swarm_msgs::node_frame_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_msgs::node_frame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 drone_id #This is drone ID!!!\n"
"uint64 keyframe_id\n"
"\n"
"geometry_msgs/Point position\n"
"geometry_msgs/Point velocity\n"
"float32 yaw\n"
"float32 pitch\n"
"float32 roll\n"
"geometry_msgs/Quaternion quat\n"
"\n"
"bool vo_available\n"
"int32[] dismap_ids\n"
"float64[] dismap_dists\n"
"node_detected_xyzyaw[] detected_xyzyaws\n"
"node_detected[] detected\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: swarm_msgs/node_detected_xyzyaw\n"
"Header header\n"
"int64 id\n"
"int32 self_drone_id\n"
"int32 remote_drone_id\n"
"geometry_msgs/Point dpos\n"
"geometry_msgs/Point dpos_std\n"
"\n"
"float64 dyaw\n"
"float64 dyaw_cov\n"
"bool enable_scale\n"
"bool is_yaw_valid\n"
"float64 probaility\n"
"float64 inv_dep\n"
"\n"
"geometry_msgs/Pose local_pose_self #Here is camera pose, not IMU pose.\n"
"geometry_msgs/Pose local_pose_remote\n"
"\n"
"geometry_msgs/Pose camera_extrinsic\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: swarm_msgs/node_detected\n"
"Header header\n"
"int64 id\n"
"int32 self_drone_id\n"
"int32 remote_drone_id\n"
"geometry_msgs/PoseWithCovariance relative_pose #If 2d detect, gives x=1\n"
"bool is_2d_detect\n"
"bool is_yaw_valid\n"
"float64 probaility\n"
"geometry_msgs/Pose local_pose_self\n"
"geometry_msgs/Pose local_pose_remote\n"
"bool dof_4\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
;
  }

  static const char* value(const ::swarm_msgs::node_frame_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_msgs::node_frame_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.drone_id);
      stream.next(m.keyframe_id);
      stream.next(m.position);
      stream.next(m.velocity);
      stream.next(m.yaw);
      stream.next(m.pitch);
      stream.next(m.roll);
      stream.next(m.quat);
      stream.next(m.vo_available);
      stream.next(m.dismap_ids);
      stream.next(m.dismap_dists);
      stream.next(m.detected_xyzyaws);
      stream.next(m.detected);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct node_frame_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_msgs::node_frame_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_msgs::node_frame_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "drone_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.drone_id);
    s << indent << "keyframe_id: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.keyframe_id);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "quat: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.quat);
    s << indent << "vo_available: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.vo_available);
    s << indent << "dismap_ids[]" << std::endl;
    for (size_t i = 0; i < v.dismap_ids.size(); ++i)
    {
      s << indent << "  dismap_ids[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.dismap_ids[i]);
    }
    s << indent << "dismap_dists[]" << std::endl;
    for (size_t i = 0; i < v.dismap_dists.size(); ++i)
    {
      s << indent << "  dismap_dists[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.dismap_dists[i]);
    }
    s << indent << "detected_xyzyaws[]" << std::endl;
    for (size_t i = 0; i < v.detected_xyzyaws.size(); ++i)
    {
      s << indent << "  detected_xyzyaws[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::swarm_msgs::node_detected_xyzyaw_<ContainerAllocator> >::stream(s, indent + "    ", v.detected_xyzyaws[i]);
    }
    s << indent << "detected[]" << std::endl;
    for (size_t i = 0; i < v.detected.size(); ++i)
    {
      s << indent << "  detected[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::swarm_msgs::node_detected_<ContainerAllocator> >::stream(s, indent + "    ", v.detected[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_MSGS_MESSAGE_NODE_FRAME_H
