// Generated by gencpp from file swarm_msgs/node_detected.msg
// DO NOT EDIT!


#ifndef SWARM_MSGS_MESSAGE_NODE_DETECTED_H
#define SWARM_MSGS_MESSAGE_NODE_DETECTED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/PoseWithCovariance.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>

namespace swarm_msgs
{
template <class ContainerAllocator>
struct node_detected_
{
  typedef node_detected_<ContainerAllocator> Type;

  node_detected_()
    : header()
    , id(0)
    , self_drone_id(0)
    , remote_drone_id(0)
    , relative_pose()
    , is_2d_detect(false)
    , is_yaw_valid(false)
    , probaility(0.0)
    , local_pose_self()
    , local_pose_remote()
    , dof_4(false)  {
    }
  node_detected_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , self_drone_id(0)
    , remote_drone_id(0)
    , relative_pose(_alloc)
    , is_2d_detect(false)
    , is_yaw_valid(false)
    , probaility(0.0)
    , local_pose_self(_alloc)
    , local_pose_remote(_alloc)
    , dof_4(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int64_t _id_type;
  _id_type id;

   typedef int32_t _self_drone_id_type;
  _self_drone_id_type self_drone_id;

   typedef int32_t _remote_drone_id_type;
  _remote_drone_id_type remote_drone_id;

   typedef  ::geometry_msgs::PoseWithCovariance_<ContainerAllocator>  _relative_pose_type;
  _relative_pose_type relative_pose;

   typedef uint8_t _is_2d_detect_type;
  _is_2d_detect_type is_2d_detect;

   typedef uint8_t _is_yaw_valid_type;
  _is_yaw_valid_type is_yaw_valid;

   typedef double _probaility_type;
  _probaility_type probaility;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _local_pose_self_type;
  _local_pose_self_type local_pose_self;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _local_pose_remote_type;
  _local_pose_remote_type local_pose_remote;

   typedef uint8_t _dof_4_type;
  _dof_4_type dof_4;





  typedef boost::shared_ptr< ::swarm_msgs::node_detected_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_msgs::node_detected_<ContainerAllocator> const> ConstPtr;

}; // struct node_detected_

typedef ::swarm_msgs::node_detected_<std::allocator<void> > node_detected;

typedef boost::shared_ptr< ::swarm_msgs::node_detected > node_detectedPtr;
typedef boost::shared_ptr< ::swarm_msgs::node_detected const> node_detectedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_msgs::node_detected_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_msgs::node_detected_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm_msgs::node_detected_<ContainerAllocator1> & lhs, const ::swarm_msgs::node_detected_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.id == rhs.id &&
    lhs.self_drone_id == rhs.self_drone_id &&
    lhs.remote_drone_id == rhs.remote_drone_id &&
    lhs.relative_pose == rhs.relative_pose &&
    lhs.is_2d_detect == rhs.is_2d_detect &&
    lhs.is_yaw_valid == rhs.is_yaw_valid &&
    lhs.probaility == rhs.probaility &&
    lhs.local_pose_self == rhs.local_pose_self &&
    lhs.local_pose_remote == rhs.local_pose_remote &&
    lhs.dof_4 == rhs.dof_4;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm_msgs::node_detected_<ContainerAllocator1> & lhs, const ::swarm_msgs::node_detected_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarm_msgs::node_detected_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_msgs::node_detected_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_msgs::node_detected_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_msgs::node_detected_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_msgs::node_detected_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_msgs::node_detected_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_msgs::node_detected_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d83c2e1345fc81767f3cd9584b06399b";
  }

  static const char* value(const ::swarm_msgs::node_detected_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd83c2e1345fc8176ULL;
  static const uint64_t static_value2 = 0x7f3cd9584b06399bULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_msgs::node_detected_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_msgs/node_detected";
  }

  static const char* value(const ::swarm_msgs::node_detected_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_msgs::node_detected_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int64 id\n"
"int32 self_drone_id\n"
"int32 remote_drone_id\n"
"geometry_msgs/PoseWithCovariance relative_pose #If 2d detect, gives x=1\n"
"bool is_2d_detect\n"
"bool is_yaw_valid\n"
"float64 probaility\n"
"geometry_msgs/Pose local_pose_self\n"
"geometry_msgs/Pose local_pose_remote\n"
"bool dof_4\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::swarm_msgs::node_detected_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_msgs::node_detected_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.self_drone_id);
      stream.next(m.remote_drone_id);
      stream.next(m.relative_pose);
      stream.next(m.is_2d_detect);
      stream.next(m.is_yaw_valid);
      stream.next(m.probaility);
      stream.next(m.local_pose_self);
      stream.next(m.local_pose_remote);
      stream.next(m.dof_4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct node_detected_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_msgs::node_detected_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_msgs::node_detected_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id);
    s << indent << "self_drone_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.self_drone_id);
    s << indent << "remote_drone_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.remote_drone_id);
    s << indent << "relative_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseWithCovariance_<ContainerAllocator> >::stream(s, indent + "  ", v.relative_pose);
    s << indent << "is_2d_detect: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_2d_detect);
    s << indent << "is_yaw_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_yaw_valid);
    s << indent << "probaility: ";
    Printer<double>::stream(s, indent + "  ", v.probaility);
    s << indent << "local_pose_self: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.local_pose_self);
    s << indent << "local_pose_remote: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.local_pose_remote);
    s << indent << "dof_4: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dof_4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_MSGS_MESSAGE_NODE_DETECTED_H
