// Generated by gencpp from file swarm_msgs/node_detected_xyzyaw.msg
// DO NOT EDIT!


#ifndef SWARM_MSGS_MESSAGE_NODE_DETECTED_XYZYAW_H
#define SWARM_MSGS_MESSAGE_NODE_DETECTED_XYZYAW_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>

namespace swarm_msgs
{
template <class ContainerAllocator>
struct node_detected_xyzyaw_
{
  typedef node_detected_xyzyaw_<ContainerAllocator> Type;

  node_detected_xyzyaw_()
    : header()
    , id(0)
    , self_drone_id(0)
    , remote_drone_id(0)
    , dpos()
    , dpos_std()
    , dyaw(0.0)
    , dyaw_cov(0.0)
    , enable_scale(false)
    , is_yaw_valid(false)
    , probaility(0.0)
    , inv_dep(0.0)
    , local_pose_self()
    , local_pose_remote()
    , camera_extrinsic()  {
    }
  node_detected_xyzyaw_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , self_drone_id(0)
    , remote_drone_id(0)
    , dpos(_alloc)
    , dpos_std(_alloc)
    , dyaw(0.0)
    , dyaw_cov(0.0)
    , enable_scale(false)
    , is_yaw_valid(false)
    , probaility(0.0)
    , inv_dep(0.0)
    , local_pose_self(_alloc)
    , local_pose_remote(_alloc)
    , camera_extrinsic(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int64_t _id_type;
  _id_type id;

   typedef int32_t _self_drone_id_type;
  _self_drone_id_type self_drone_id;

   typedef int32_t _remote_drone_id_type;
  _remote_drone_id_type remote_drone_id;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _dpos_type;
  _dpos_type dpos;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _dpos_std_type;
  _dpos_std_type dpos_std;

   typedef double _dyaw_type;
  _dyaw_type dyaw;

   typedef double _dyaw_cov_type;
  _dyaw_cov_type dyaw_cov;

   typedef uint8_t _enable_scale_type;
  _enable_scale_type enable_scale;

   typedef uint8_t _is_yaw_valid_type;
  _is_yaw_valid_type is_yaw_valid;

   typedef double _probaility_type;
  _probaility_type probaility;

   typedef double _inv_dep_type;
  _inv_dep_type inv_dep;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _local_pose_self_type;
  _local_pose_self_type local_pose_self;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _local_pose_remote_type;
  _local_pose_remote_type local_pose_remote;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _camera_extrinsic_type;
  _camera_extrinsic_type camera_extrinsic;





  typedef boost::shared_ptr< ::swarm_msgs::node_detected_xyzyaw_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_msgs::node_detected_xyzyaw_<ContainerAllocator> const> ConstPtr;

}; // struct node_detected_xyzyaw_

typedef ::swarm_msgs::node_detected_xyzyaw_<std::allocator<void> > node_detected_xyzyaw;

typedef boost::shared_ptr< ::swarm_msgs::node_detected_xyzyaw > node_detected_xyzyawPtr;
typedef boost::shared_ptr< ::swarm_msgs::node_detected_xyzyaw const> node_detected_xyzyawConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_msgs::node_detected_xyzyaw_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_msgs::node_detected_xyzyaw_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm_msgs::node_detected_xyzyaw_<ContainerAllocator1> & lhs, const ::swarm_msgs::node_detected_xyzyaw_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.id == rhs.id &&
    lhs.self_drone_id == rhs.self_drone_id &&
    lhs.remote_drone_id == rhs.remote_drone_id &&
    lhs.dpos == rhs.dpos &&
    lhs.dpos_std == rhs.dpos_std &&
    lhs.dyaw == rhs.dyaw &&
    lhs.dyaw_cov == rhs.dyaw_cov &&
    lhs.enable_scale == rhs.enable_scale &&
    lhs.is_yaw_valid == rhs.is_yaw_valid &&
    lhs.probaility == rhs.probaility &&
    lhs.inv_dep == rhs.inv_dep &&
    lhs.local_pose_self == rhs.local_pose_self &&
    lhs.local_pose_remote == rhs.local_pose_remote &&
    lhs.camera_extrinsic == rhs.camera_extrinsic;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm_msgs::node_detected_xyzyaw_<ContainerAllocator1> & lhs, const ::swarm_msgs::node_detected_xyzyaw_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarm_msgs::node_detected_xyzyaw_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_msgs::node_detected_xyzyaw_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_msgs::node_detected_xyzyaw_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_msgs::node_detected_xyzyaw_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_msgs::node_detected_xyzyaw_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_msgs::node_detected_xyzyaw_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_msgs::node_detected_xyzyaw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "153d8a388ec70ddfe9950d5a9c645eda";
  }

  static const char* value(const ::swarm_msgs::node_detected_xyzyaw_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x153d8a388ec70ddfULL;
  static const uint64_t static_value2 = 0xe9950d5a9c645edaULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_msgs::node_detected_xyzyaw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_msgs/node_detected_xyzyaw";
  }

  static const char* value(const ::swarm_msgs::node_detected_xyzyaw_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_msgs::node_detected_xyzyaw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int64 id\n"
"int32 self_drone_id\n"
"int32 remote_drone_id\n"
"geometry_msgs/Point dpos\n"
"geometry_msgs/Point dpos_std\n"
"\n"
"float64 dyaw\n"
"float64 dyaw_cov\n"
"bool enable_scale\n"
"bool is_yaw_valid\n"
"float64 probaility\n"
"float64 inv_dep\n"
"\n"
"geometry_msgs/Pose local_pose_self #Here is camera pose, not IMU pose.\n"
"geometry_msgs/Pose local_pose_remote\n"
"\n"
"geometry_msgs/Pose camera_extrinsic\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::swarm_msgs::node_detected_xyzyaw_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_msgs::node_detected_xyzyaw_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.self_drone_id);
      stream.next(m.remote_drone_id);
      stream.next(m.dpos);
      stream.next(m.dpos_std);
      stream.next(m.dyaw);
      stream.next(m.dyaw_cov);
      stream.next(m.enable_scale);
      stream.next(m.is_yaw_valid);
      stream.next(m.probaility);
      stream.next(m.inv_dep);
      stream.next(m.local_pose_self);
      stream.next(m.local_pose_remote);
      stream.next(m.camera_extrinsic);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct node_detected_xyzyaw_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_msgs::node_detected_xyzyaw_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_msgs::node_detected_xyzyaw_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id);
    s << indent << "self_drone_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.self_drone_id);
    s << indent << "remote_drone_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.remote_drone_id);
    s << indent << "dpos: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.dpos);
    s << indent << "dpos_std: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.dpos_std);
    s << indent << "dyaw: ";
    Printer<double>::stream(s, indent + "  ", v.dyaw);
    s << indent << "dyaw_cov: ";
    Printer<double>::stream(s, indent + "  ", v.dyaw_cov);
    s << indent << "enable_scale: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable_scale);
    s << indent << "is_yaw_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_yaw_valid);
    s << indent << "probaility: ";
    Printer<double>::stream(s, indent + "  ", v.probaility);
    s << indent << "inv_dep: ";
    Printer<double>::stream(s, indent + "  ", v.inv_dep);
    s << indent << "local_pose_self: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.local_pose_self);
    s << indent << "local_pose_remote: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.local_pose_remote);
    s << indent << "camera_extrinsic: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.camera_extrinsic);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_MSGS_MESSAGE_NODE_DETECTED_XYZYAW_H
