// Generated by gencpp from file swarm_msgs/swarm_fused_relative.msg
// DO NOT EDIT!


#ifndef SWARM_MSGS_MESSAGE_SWARM_FUSED_RELATIVE_H
#define SWARM_MSGS_MESSAGE_SWARM_FUSED_RELATIVE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Point.h>

namespace swarm_msgs
{
template <class ContainerAllocator>
struct swarm_fused_relative_
{
  typedef swarm_fused_relative_<ContainerAllocator> Type;

  swarm_fused_relative_()
    : header()
    , ids()
    , relative_drone_position()
    , relative_drone_velocity()
    , relative_drone_yaw()
    , position_cov()
    , yaw_cov()
    , self_yaw(0.0)
    , self_pos()  {
    }
  swarm_fused_relative_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ids(_alloc)
    , relative_drone_position(_alloc)
    , relative_drone_velocity(_alloc)
    , relative_drone_yaw(_alloc)
    , position_cov(_alloc)
    , yaw_cov(_alloc)
    , self_yaw(0.0)
    , self_pos(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _ids_type;
  _ids_type ids;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _relative_drone_position_type;
  _relative_drone_position_type relative_drone_position;

   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Vector3_<ContainerAllocator> >> _relative_drone_velocity_type;
  _relative_drone_velocity_type relative_drone_velocity;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _relative_drone_yaw_type;
  _relative_drone_yaw_type relative_drone_yaw;

   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Vector3_<ContainerAllocator> >> _position_cov_type;
  _position_cov_type position_cov;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _yaw_cov_type;
  _yaw_cov_type yaw_cov;

   typedef double _self_yaw_type;
  _self_yaw_type self_yaw;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _self_pos_type;
  _self_pos_type self_pos;





  typedef boost::shared_ptr< ::swarm_msgs::swarm_fused_relative_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_msgs::swarm_fused_relative_<ContainerAllocator> const> ConstPtr;

}; // struct swarm_fused_relative_

typedef ::swarm_msgs::swarm_fused_relative_<std::allocator<void> > swarm_fused_relative;

typedef boost::shared_ptr< ::swarm_msgs::swarm_fused_relative > swarm_fused_relativePtr;
typedef boost::shared_ptr< ::swarm_msgs::swarm_fused_relative const> swarm_fused_relativeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_msgs::swarm_fused_relative_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_msgs::swarm_fused_relative_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm_msgs::swarm_fused_relative_<ContainerAllocator1> & lhs, const ::swarm_msgs::swarm_fused_relative_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ids == rhs.ids &&
    lhs.relative_drone_position == rhs.relative_drone_position &&
    lhs.relative_drone_velocity == rhs.relative_drone_velocity &&
    lhs.relative_drone_yaw == rhs.relative_drone_yaw &&
    lhs.position_cov == rhs.position_cov &&
    lhs.yaw_cov == rhs.yaw_cov &&
    lhs.self_yaw == rhs.self_yaw &&
    lhs.self_pos == rhs.self_pos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm_msgs::swarm_fused_relative_<ContainerAllocator1> & lhs, const ::swarm_msgs::swarm_fused_relative_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarm_msgs::swarm_fused_relative_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_msgs::swarm_fused_relative_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_msgs::swarm_fused_relative_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_msgs::swarm_fused_relative_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_msgs::swarm_fused_relative_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_msgs::swarm_fused_relative_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_msgs::swarm_fused_relative_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1aec1b64c429b35f596e99eb4969d2f5";
  }

  static const char* value(const ::swarm_msgs::swarm_fused_relative_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1aec1b64c429b35fULL;
  static const uint64_t static_value2 = 0x596e99eb4969d2f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_msgs::swarm_fused_relative_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_msgs/swarm_fused_relative";
  }

  static const char* value(const ::swarm_msgs::swarm_fused_relative_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_msgs::swarm_fused_relative_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint32[] ids\n"
"geometry_msgs/Point[] relative_drone_position\n"
"geometry_msgs/Vector3[] relative_drone_velocity\n"
"float64[] relative_drone_yaw\n"
"\n"
"geometry_msgs/Vector3[] position_cov\n"
"float64[] yaw_cov\n"
"\n"
"float64 self_yaw\n"
"geometry_msgs/Point self_pos\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::swarm_msgs::swarm_fused_relative_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_msgs::swarm_fused_relative_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ids);
      stream.next(m.relative_drone_position);
      stream.next(m.relative_drone_velocity);
      stream.next(m.relative_drone_yaw);
      stream.next(m.position_cov);
      stream.next(m.yaw_cov);
      stream.next(m.self_yaw);
      stream.next(m.self_pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct swarm_fused_relative_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_msgs::swarm_fused_relative_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_msgs::swarm_fused_relative_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ids[]" << std::endl;
    for (size_t i = 0; i < v.ids.size(); ++i)
    {
      s << indent << "  ids[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.ids[i]);
    }
    s << indent << "relative_drone_position[]" << std::endl;
    for (size_t i = 0; i < v.relative_drone_position.size(); ++i)
    {
      s << indent << "  relative_drone_position[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.relative_drone_position[i]);
    }
    s << indent << "relative_drone_velocity[]" << std::endl;
    for (size_t i = 0; i < v.relative_drone_velocity.size(); ++i)
    {
      s << indent << "  relative_drone_velocity[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "    ", v.relative_drone_velocity[i]);
    }
    s << indent << "relative_drone_yaw[]" << std::endl;
    for (size_t i = 0; i < v.relative_drone_yaw.size(); ++i)
    {
      s << indent << "  relative_drone_yaw[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.relative_drone_yaw[i]);
    }
    s << indent << "position_cov[]" << std::endl;
    for (size_t i = 0; i < v.position_cov.size(); ++i)
    {
      s << indent << "  position_cov[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "    ", v.position_cov[i]);
    }
    s << indent << "yaw_cov[]" << std::endl;
    for (size_t i = 0; i < v.yaw_cov.size(); ++i)
    {
      s << indent << "  yaw_cov[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.yaw_cov[i]);
    }
    s << indent << "self_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.self_yaw);
    s << indent << "self_pos: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.self_pos);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_MSGS_MESSAGE_SWARM_FUSED_RELATIVE_H
