// Generated by gencpp from file swarm_msgs/swarm_remote_command.msg
// DO NOT EDIT!


#ifndef SWARM_MSGS_MESSAGE_SWARM_REMOTE_COMMAND_H
#define SWARM_MSGS_MESSAGE_SWARM_REMOTE_COMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <swarmtal_msgs/drone_onboard_command.h>

namespace swarm_msgs
{
template <class ContainerAllocator>
struct swarm_remote_command_
{
  typedef swarm_remote_command_<ContainerAllocator> Type;

  swarm_remote_command_()
    : target_id(0)
    , cmd()  {
    }
  swarm_remote_command_(const ContainerAllocator& _alloc)
    : target_id(0)
    , cmd(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _target_id_type;
  _target_id_type target_id;

   typedef  ::swarmtal_msgs::drone_onboard_command_<ContainerAllocator>  _cmd_type;
  _cmd_type cmd;





  typedef boost::shared_ptr< ::swarm_msgs::swarm_remote_command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_msgs::swarm_remote_command_<ContainerAllocator> const> ConstPtr;

}; // struct swarm_remote_command_

typedef ::swarm_msgs::swarm_remote_command_<std::allocator<void> > swarm_remote_command;

typedef boost::shared_ptr< ::swarm_msgs::swarm_remote_command > swarm_remote_commandPtr;
typedef boost::shared_ptr< ::swarm_msgs::swarm_remote_command const> swarm_remote_commandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_msgs::swarm_remote_command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_msgs::swarm_remote_command_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm_msgs::swarm_remote_command_<ContainerAllocator1> & lhs, const ::swarm_msgs::swarm_remote_command_<ContainerAllocator2> & rhs)
{
  return lhs.target_id == rhs.target_id &&
    lhs.cmd == rhs.cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm_msgs::swarm_remote_command_<ContainerAllocator1> & lhs, const ::swarm_msgs::swarm_remote_command_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarm_msgs::swarm_remote_command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_msgs::swarm_remote_command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_msgs::swarm_remote_command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_msgs::swarm_remote_command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_msgs::swarm_remote_command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_msgs::swarm_remote_command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_msgs::swarm_remote_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "168acc9c69f67b2e7b4a0220dae289b1";
  }

  static const char* value(const ::swarm_msgs::swarm_remote_command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x168acc9c69f67b2eULL;
  static const uint64_t static_value2 = 0x7b4a0220dae289b1ULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_msgs::swarm_remote_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_msgs/swarm_remote_command";
  }

  static const char* value(const ::swarm_msgs::swarm_remote_command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_msgs::swarm_remote_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#When target id==-1, that is send to all\n"
"int32 target_id\n"
"swarmtal_msgs/drone_onboard_command cmd\n"
"================================================================================\n"
"MSG: swarmtal_msgs/drone_onboard_command\n"
"uint32 CTRL_POS_COMMAND=0\n"
"uint32 CTRL_VEL_COMMAND=1\n"
"uint32 CTRL_ATT_COMMAND=2\n"
"uint32 CTRL_MISSION_LOAD_COMMAND=3\n"
"uint32 CTRL_MISSION_END_COMMAND=4\n"
"uint32 CTRL_TAKEOF_COMMAND=5\n"
"uint32 CTRL_LANDING_COMMAND=6\n"
"uint32 CTRL_HOVER_COMMAND=7\n"
"uint32 CTRL_ARM_COMMAND=8\n"
"\n"
"uint32 CTRL_PLANING_TGT_COMMAND=10\n"
"\n"
"uint32 CTRL_FORMATION_IDLE=11\n"
"\n"
"#Passive hold in master's local frame\n"
"uint32 CTRL_FORMATION_HOLD_0=12\n"
"\n"
"#Passive hold in master's natural frame\n"
"uint32 CTRL_FORMATION_HOLD_1=13\n"
"\n"
"#Activate fly in master's local frame\n"
"uint32 CTRL_FORMATION_FLY_0=14\n"
"\n"
"#Activate fly master's natural frame\n"
"uint32 CTRL_FORMATION_FLY_1=15\n"
"\n"
"uint32 CTRL_SPEC_TRAJS=16\n"
"uint32 CTRL_MISSION_TRAJS=20\n"
"\n"
"uint32 CTRL_TASK_EXPROLARATION=30\n"
"\n"
"uint32 CTRL_END_MISSION=99\n"
"\n"
"\n"
"uint32 command_type\n"
"#For formation param1 is id\n"
"#Param 2 is submodule\n"
"#3, 4, 5 is x y z\n"
"#Param 6 is yaw\n"
"\n"
"# For POS param1 2 3 is x y z * 10000 \n"
"# 4 is yaw*10000 if yaw =666666, then use last yawsp\n"
"# 567 is vel feedforward 8 9 10\n"
"\n"
"# For VEL param1 2 3 is x y z * 10000 \n"
"# 4 is yaw*10000 if yaw =666666, then use last yawsp\n"
"\n"
"# For ATT \n"
"# param1 2 3 4 is roll pitch yaw vz * 10000 \n"
"# 5 (>0 use thrust else z is velz)\n"
"# 6 (>0 use yaw else yawrate) \n"
"# For TAKEoff param 1 is takeoff height * 10000\n"
"# For arm param = 0 is disarm param>0 is arm\n"
"# For mission param1-7 is  mission id\n"
"\n"
"#For Spec traj, \n"
"# param1 is spec traj type 0 is disable. 1 is 8. \n"
"# param2 if enable yaw\n"
"# param3 T*10000\n"
"# param4 ox * 10000\n"
"# param5 oy * 10000\n"
"# param6 oz * 10000\n"
"\n"
"int32 param1\n"
"int32 param2\n"
"int32 param3\n"
"int32 param4\n"
"int32 param5\n"
"int32 param6\n"
"int32 param7\n"
"int32 param8\n"
"int32 param9\n"
"int32 param10\n"
;
  }

  static const char* value(const ::swarm_msgs::swarm_remote_command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_msgs::swarm_remote_command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_id);
      stream.next(m.cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct swarm_remote_command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_msgs::swarm_remote_command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_msgs::swarm_remote_command_<ContainerAllocator>& v)
  {
    s << indent << "target_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.target_id);
    s << indent << "cmd: ";
    s << std::endl;
    Printer< ::swarmtal_msgs::drone_onboard_command_<ContainerAllocator> >::stream(s, indent + "  ", v.cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_MSGS_MESSAGE_SWARM_REMOTE_COMMAND_H
