// Generated by gencpp from file swarm_msgs/swarm_drone_source_data.msg
// DO NOT EDIT!


#ifndef SWARM_MSGS_MESSAGE_SWARM_DRONE_SOURCE_DATA_H
#define SWARM_MSGS_MESSAGE_SWARM_DRONE_SOURCE_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <nav_msgs/Odometry.h>

namespace swarm_msgs
{
template <class ContainerAllocator>
struct swarm_drone_source_data_
{
  typedef swarm_drone_source_data_<ContainerAllocator> Type;

  swarm_drone_source_data_()
    : header()
    , drone_num(0)
    , self_id(0)
    , drone_self_odoms()
    , ids()
    , active()
    , distance_matrix()
    , distance_time()
    , self_frame_id()  {
    }
  swarm_drone_source_data_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , drone_num(0)
    , self_id(0)
    , drone_self_odoms(_alloc)
    , ids(_alloc)
    , active(_alloc)
    , distance_matrix(_alloc)
    , distance_time(_alloc)
    , self_frame_id(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _drone_num_type;
  _drone_num_type drone_num;

   typedef uint32_t _self_id_type;
  _self_id_type self_id;

   typedef std::vector< ::nav_msgs::Odometry_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::nav_msgs::Odometry_<ContainerAllocator> >> _drone_self_odoms_type;
  _drone_self_odoms_type drone_self_odoms;

   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _ids_type;
  _ids_type ids;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _active_type;
  _active_type active;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _distance_matrix_type;
  _distance_matrix_type distance_matrix;

   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _distance_time_type;
  _distance_time_type distance_time;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _self_frame_id_type;
  _self_frame_id_type self_frame_id;





  typedef boost::shared_ptr< ::swarm_msgs::swarm_drone_source_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_msgs::swarm_drone_source_data_<ContainerAllocator> const> ConstPtr;

}; // struct swarm_drone_source_data_

typedef ::swarm_msgs::swarm_drone_source_data_<std::allocator<void> > swarm_drone_source_data;

typedef boost::shared_ptr< ::swarm_msgs::swarm_drone_source_data > swarm_drone_source_dataPtr;
typedef boost::shared_ptr< ::swarm_msgs::swarm_drone_source_data const> swarm_drone_source_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_msgs::swarm_drone_source_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_msgs::swarm_drone_source_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm_msgs::swarm_drone_source_data_<ContainerAllocator1> & lhs, const ::swarm_msgs::swarm_drone_source_data_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.drone_num == rhs.drone_num &&
    lhs.self_id == rhs.self_id &&
    lhs.drone_self_odoms == rhs.drone_self_odoms &&
    lhs.ids == rhs.ids &&
    lhs.active == rhs.active &&
    lhs.distance_matrix == rhs.distance_matrix &&
    lhs.distance_time == rhs.distance_time &&
    lhs.self_frame_id == rhs.self_frame_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm_msgs::swarm_drone_source_data_<ContainerAllocator1> & lhs, const ::swarm_msgs::swarm_drone_source_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarm_msgs::swarm_drone_source_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_msgs::swarm_drone_source_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_msgs::swarm_drone_source_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_msgs::swarm_drone_source_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_msgs::swarm_drone_source_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_msgs::swarm_drone_source_data_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_msgs::swarm_drone_source_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed292949bcc7aff7a6c1948c5595d627";
  }

  static const char* value(const ::swarm_msgs::swarm_drone_source_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xed292949bcc7aff7ULL;
  static const uint64_t static_value2 = 0xa6c1948c5595d627ULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_msgs::swarm_drone_source_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_msgs/swarm_drone_source_data";
  }

  static const char* value(const ::swarm_msgs::swarm_drone_source_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_msgs::swarm_drone_source_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 drone_num\n"
"uint32 self_id\n"
"nav_msgs/Odometry[] drone_self_odoms\n"
"uint32[] ids\n"
"bool[] active\n"
"float32[] distance_matrix\n"
"uint32[] distance_time\n"
"string self_frame_id\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/Odometry\n"
"# This represents an estimate of a position and velocity in free space.  \n"
"# The pose in this message should be specified in the coordinate frame given by header.frame_id.\n"
"# The twist in this message should be specified in the coordinate frame given by the child_frame_id\n"
"Header header\n"
"string child_frame_id\n"
"geometry_msgs/PoseWithCovariance pose\n"
"geometry_msgs/TwistWithCovariance twist\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TwistWithCovariance\n"
"# This expresses velocity in free space with uncertainty.\n"
"\n"
"Twist twist\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::swarm_msgs::swarm_drone_source_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_msgs::swarm_drone_source_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.drone_num);
      stream.next(m.self_id);
      stream.next(m.drone_self_odoms);
      stream.next(m.ids);
      stream.next(m.active);
      stream.next(m.distance_matrix);
      stream.next(m.distance_time);
      stream.next(m.self_frame_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct swarm_drone_source_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_msgs::swarm_drone_source_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_msgs::swarm_drone_source_data_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "drone_num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.drone_num);
    s << indent << "self_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.self_id);
    s << indent << "drone_self_odoms[]" << std::endl;
    for (size_t i = 0; i < v.drone_self_odoms.size(); ++i)
    {
      s << indent << "  drone_self_odoms[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::nav_msgs::Odometry_<ContainerAllocator> >::stream(s, indent + "    ", v.drone_self_odoms[i]);
    }
    s << indent << "ids[]" << std::endl;
    for (size_t i = 0; i < v.ids.size(); ++i)
    {
      s << indent << "  ids[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.ids[i]);
    }
    s << indent << "active[]" << std::endl;
    for (size_t i = 0; i < v.active.size(); ++i)
    {
      s << indent << "  active[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.active[i]);
    }
    s << indent << "distance_matrix[]" << std::endl;
    for (size_t i = 0; i < v.distance_matrix.size(); ++i)
    {
      s << indent << "  distance_matrix[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.distance_matrix[i]);
    }
    s << indent << "distance_time[]" << std::endl;
    for (size_t i = 0; i < v.distance_time.size(); ++i)
    {
      s << indent << "  distance_time[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.distance_time[i]);
    }
    s << indent << "self_frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.self_frame_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_MSGS_MESSAGE_SWARM_DRONE_SOURCE_DATA_H
