(cl:in-package swarmtal_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          POSE-VAL
          POSE
          IMU_DATA-VAL
          IMU_DATA
          PITCH_CMD-VAL
          PITCH_CMD
          ROLL_CMD-VAL
          ROLL_CMD
          YAW_CMD-VAL
          YAW_CMD
          THRUST_CMD-VAL
          THRUST_CMD
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          YAW-VAL
          YAW
          YAW_SP-VAL
          YAW_SP
          ACC_CMD-VAL
          ACC_CMD
          VEL_CMD-VAL
          VEL_CMD
          GLOBAL_VEL-VAL
          GLOBAL_VEL
          POS_SP-VAL
          POS_SP
          CTRL_MODE-VAL
          CTRL_MODE
          USE_FC_YAW-VAL
          USE_FC_YAW
          COUNT-VAL
          COUNT
          MAX_VEL-VAL
          MAX_VEL
))