(cl:in-package swarmtal_msgs-msg)
(cl:export '(CTRL_INPUT_STATE-VAL
          CTRL_INPUT_STATE
          FLIGHT_STATUS-VAL
          FLIGHT_STATUS
          CONTROL_AUTH-VAL
          CONTROL_AUTH
          TAKEOFF_TARGET_HEIGHT-VAL
          TAKEOFF_TARGET_HEIGHT
          TAKEOFF_VELOCITY-VAL
          TAKEOFF_VELOCITY
          VO_LATENCY-VAL
          VO_LATENCY
          LANDING_MODE-VAL
          LANDING_MODE
          LANDING_VELOCITY-VAL
          LANDING_VELOCITY
          COMMANDER_CTRL_MODE-VAL
          COMMANDER_CTRL_MODE
          BAT_VOL-VAL
          BAT_VOL
          BAT_REMAIN-VAL
          BAT_REMAIN
          IS_ARMED-VAL
          IS_ARMED
          RC_VALID-VAL
          RC_VALID
          ONBOARD_CMD_VALID-VAL
          ONBOARD_CMD_VALID
          VO_VALID-VAL
          VO_VALID
          DJISDK_VALID-VAL
          DJISDK_VALID
          POS-VAL
          POS
          VEL-VAL
          VEL
          YAW-VAL
          YAW
          CTRL_CMD-VAL
          CTRL_CMD
          IMU_DATA-VAL
          IMU_DATA
))