// Generated by gencpp from file epic_planner/GoalService.msg
// DO NOT EDIT!


#ifndef EPIC_PLANNER_MESSAGE_GOALSERVICE_H
#define EPIC_PLANNER_MESSAGE_GOALSERVICE_H

#include <ros/service_traits.h>


#include <epic_planner/GoalServiceRequest.h>
#include <epic_planner/GoalServiceResponse.h>


namespace epic_planner
{

struct GoalService
{

typedef GoalServiceRequest Request;
typedef GoalServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoalService
} // namespace epic_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::epic_planner::GoalService > {
  static const char* value()
  {
    return "adda1280f83d6408fe1b7382c0bc294d";
  }

  static const char* value(const ::epic_planner::GoalService&) { return value(); }
};

template<>
struct DataType< ::epic_planner::GoalService > {
  static const char* value()
  {
    return "epic_planner/GoalService";
  }

  static const char* value(const ::epic_planner::GoalService&) { return value(); }
};


// service_traits::MD5Sum< ::epic_planner::GoalServiceRequest> should match
// service_traits::MD5Sum< ::epic_planner::GoalService >
template<>
struct MD5Sum< ::epic_planner::GoalServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::epic_planner::GoalService >::value();
  }
  static const char* value(const ::epic_planner::GoalServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::epic_planner::GoalServiceRequest> should match
// service_traits::DataType< ::epic_planner::GoalService >
template<>
struct DataType< ::epic_planner::GoalServiceRequest>
{
  static const char* value()
  {
    return DataType< ::epic_planner::GoalService >::value();
  }
  static const char* value(const ::epic_planner::GoalServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::epic_planner::GoalServiceResponse> should match
// service_traits::MD5Sum< ::epic_planner::GoalService >
template<>
struct MD5Sum< ::epic_planner::GoalServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::epic_planner::GoalService >::value();
  }
  static const char* value(const ::epic_planner::GoalServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::epic_planner::GoalServiceResponse> should match
// service_traits::DataType< ::epic_planner::GoalService >
template<>
struct DataType< ::epic_planner::GoalServiceResponse>
{
  static const char* value()
  {
    return DataType< ::epic_planner::GoalService >::value();
  }
  static const char* value(const ::epic_planner::GoalServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EPIC_PLANNER_MESSAGE_GOALSERVICE_H
