// Generated by gencpp from file epic_planner/GoalServiceResponse.msg
// DO NOT EDIT!


#ifndef EPIC_PLANNER_MESSAGE_GOALSERVICERESPONSE_H
#define EPIC_PLANNER_MESSAGE_GOALSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace epic_planner
{
template <class ContainerAllocator>
struct GoalServiceResponse_
{
  typedef GoalServiceResponse_<ContainerAllocator> Type;

  GoalServiceResponse_()
    : success(false)
    , message()  {
    }
  GoalServiceResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::epic_planner::GoalServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::epic_planner::GoalServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GoalServiceResponse_

typedef ::epic_planner::GoalServiceResponse_<std::allocator<void> > GoalServiceResponse;

typedef boost::shared_ptr< ::epic_planner::GoalServiceResponse > GoalServiceResponsePtr;
typedef boost::shared_ptr< ::epic_planner::GoalServiceResponse const> GoalServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::epic_planner::GoalServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::epic_planner::GoalServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::epic_planner::GoalServiceResponse_<ContainerAllocator1> & lhs, const ::epic_planner::GoalServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::epic_planner::GoalServiceResponse_<ContainerAllocator1> & lhs, const ::epic_planner::GoalServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace epic_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::epic_planner::GoalServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::epic_planner::GoalServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::epic_planner::GoalServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::epic_planner::GoalServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::epic_planner::GoalServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::epic_planner::GoalServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::epic_planner::GoalServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::epic_planner::GoalServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::epic_planner::GoalServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "epic_planner/GoalServiceResponse";
  }

  static const char* value(const ::epic_planner::GoalServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::epic_planner::GoalServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::epic_planner::GoalServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::epic_planner::GoalServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoalServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::epic_planner::GoalServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::epic_planner::GoalServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EPIC_PLANNER_MESSAGE_GOALSERVICERESPONSE_H
