// Generated by gencpp from file epic_planner/GoalServiceRequest.msg
// DO NOT EDIT!


#ifndef EPIC_PLANNER_MESSAGE_GOALSERVICEREQUEST_H
#define EPIC_PLANNER_MESSAGE_GOALSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace epic_planner
{
template <class ContainerAllocator>
struct GoalServiceRequest_
{
  typedef GoalServiceRequest_<ContainerAllocator> Type;

  GoalServiceRequest_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)  {
    }
  GoalServiceRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::epic_planner::GoalServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::epic_planner::GoalServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GoalServiceRequest_

typedef ::epic_planner::GoalServiceRequest_<std::allocator<void> > GoalServiceRequest;

typedef boost::shared_ptr< ::epic_planner::GoalServiceRequest > GoalServiceRequestPtr;
typedef boost::shared_ptr< ::epic_planner::GoalServiceRequest const> GoalServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::epic_planner::GoalServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::epic_planner::GoalServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::epic_planner::GoalServiceRequest_<ContainerAllocator1> & lhs, const ::epic_planner::GoalServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::epic_planner::GoalServiceRequest_<ContainerAllocator1> & lhs, const ::epic_planner::GoalServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace epic_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::epic_planner::GoalServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::epic_planner::GoalServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::epic_planner::GoalServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::epic_planner::GoalServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::epic_planner::GoalServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::epic_planner::GoalServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::epic_planner::GoalServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "52d0ade995d52d04cae303675aa442a7";
  }

  static const char* value(const ::epic_planner::GoalServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x52d0ade995d52d04ULL;
  static const uint64_t static_value2 = 0xcae303675aa442a7ULL;
};

template<class ContainerAllocator>
struct DataType< ::epic_planner::GoalServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "epic_planner/GoalServiceRequest";
  }

  static const char* value(const ::epic_planner::GoalServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::epic_planner::GoalServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 yaw\n"
;
  }

  static const char* value(const ::epic_planner::GoalServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::epic_planner::GoalServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoalServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::epic_planner::GoalServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::epic_planner::GoalServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EPIC_PLANNER_MESSAGE_GOALSERVICEREQUEST_H
