(cl:in-package swarm_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          DRONE_ID-VAL
          DRONE_ID
          FEATURE_DESCRIPTOR-VAL
          FEATURE_DESCRIPTOR
          POSE_DRONE-VAL
          POSE_DRONE
          CAMERA_EXTRINSIC-VAL
          CAMERA_EXTRINSIC
          IMAGE_DESC-VAL
          IMAGE_DESC
          IMAGE_WIDTH-VAL
          IMAGE_WIDTH
          IMAGE_HEIGHT-VAL
          IMAGE_HEIGHT
          IMAGE-VAL
          IMAGE
          LANDMARKS_2D_NORM-VAL
          LANDMARKS_2D_NORM
          LANDMARKS_2D-VAL
          LANDMARKS_2D
          LANDMARKS_3D-VAL
          LANDMARKS_3D
          LANDMARKS_FLAG-VAL
          LANDMARKS_FLAG
          PREVENT_ADDING_DB-VAL
          PREVENT_ADDING_DB
          DIRECTION-VAL
          DIRECTION
))