(cl:in-package swarm_msgs-msg)
(cl:export '(TS_A-VAL
          TS_A
          TS_B-VAL
          TS_B
          DRONE_ID_A-VAL
          DRONE_ID_A
          DRONE_ID_B-VAL
          DRONE_ID_B
          KEYFRAME_ID_A-VAL
          KEYFRAME_ID_A
          KEYFRAME_ID_B-VAL
          KEYFRAME_ID_B
          RELATIVE_POSE-VAL
          RELATIVE_POSE
          SELF_POSE_A-VAL
          SELF_POSE_A
          SELF_POSE_B-VAL
          SELF_POSE_B
          POS_COV-VAL
          POS_COV
          ANG_COV-VAL
          ANG_COV
          PNP_INLIER_NUM-VAL
          PNP_INLIER_NUM
          IS_4DOF-VAL
          IS_4DOF
          ID-VAL
          ID
))