(cl:in-package swarm_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          DRONE_ID-VAL
          DRONE_ID
          KEYFRAME_ID-VAL
          KEYFRAME_ID
          POSITION-VAL
          POSITION
          VELOCITY-VAL
          VELOCITY
          YAW-VAL
          YAW
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          QUAT-VAL
          QUAT
          VO_AVAILABLE-VAL
          VO_AVAILABLE
          DISMAP_IDS-VAL
          DISMAP_IDS
          DISMAP_DISTS-VAL
          DISMAP_DISTS
          DETECTED_XYZYAWS-VAL
          DETECTED_XYZYAWS
          DETECTED-VAL
          DETECTED
))