(cl:in-package swarm_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ID-VAL
          ID
          SELF_DRONE_ID-VAL
          SELF_DRONE_ID
          REMOTE_DRONE_ID-VAL
          REMOTE_DRONE_ID
          DPOS-VAL
          DPOS
          DPOS_STD-VAL
          DPOS_STD
          DYAW-VAL
          DYAW
          DYAW_COV-VAL
          DYAW_COV
          ENABLE_SCALE-VAL
          ENABLE_SCALE
          IS_YAW_VALID-VAL
          IS_YAW_VALID
          PROBAILITY-VAL
          PROBAILITY
          INV_DEP-VAL
          INV_DEP
          LOCAL_POSE_SELF-VAL
          LOCAL_POSE_SELF
          LOCAL_POSE_REMOTE-VAL
          LOCAL_POSE_REMOTE
          CAMERA_EXTRINSIC-VAL
          CAMERA_EXTRINSIC
))