// Generated by gencpp from file swarmcomm_msgs/data_buffer.msg
// DO NOT EDIT!


#ifndef SWARMCOMM_MSGS_MESSAGE_DATA_BUFFER_H
#define SWARMCOMM_MSGS_MESSAGE_DATA_BUFFER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace swarmcomm_msgs
{
template <class ContainerAllocator>
struct data_buffer_
{
  typedef data_buffer_<ContainerAllocator> Type;

  data_buffer_()
    : header()
    , data()
    , send_method(0)  {
    }
  data_buffer_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(_alloc)
    , send_method(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _data_type;
  _data_type data;

   typedef uint8_t _send_method_type;
  _send_method_type send_method;





  typedef boost::shared_ptr< ::swarmcomm_msgs::data_buffer_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarmcomm_msgs::data_buffer_<ContainerAllocator> const> ConstPtr;

}; // struct data_buffer_

typedef ::swarmcomm_msgs::data_buffer_<std::allocator<void> > data_buffer;

typedef boost::shared_ptr< ::swarmcomm_msgs::data_buffer > data_bufferPtr;
typedef boost::shared_ptr< ::swarmcomm_msgs::data_buffer const> data_bufferConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarmcomm_msgs::data_buffer_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarmcomm_msgs::data_buffer_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarmcomm_msgs::data_buffer_<ContainerAllocator1> & lhs, const ::swarmcomm_msgs::data_buffer_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.data == rhs.data &&
    lhs.send_method == rhs.send_method;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarmcomm_msgs::data_buffer_<ContainerAllocator1> & lhs, const ::swarmcomm_msgs::data_buffer_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarmcomm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarmcomm_msgs::data_buffer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarmcomm_msgs::data_buffer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarmcomm_msgs::data_buffer_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarmcomm_msgs::data_buffer_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarmcomm_msgs::data_buffer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarmcomm_msgs::data_buffer_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarmcomm_msgs::data_buffer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b57009adb212892c421cbf75aa66757f";
  }

  static const char* value(const ::swarmcomm_msgs::data_buffer_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb57009adb212892cULL;
  static const uint64_t static_value2 = 0x421cbf75aa66757fULL;
};

template<class ContainerAllocator>
struct DataType< ::swarmcomm_msgs::data_buffer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarmcomm_msgs/data_buffer";
  }

  static const char* value(const ::swarmcomm_msgs::data_buffer_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarmcomm_msgs::data_buffer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint8[] data\n"
"\n"
"#0 UWB 1 WiFI 2 All\n"
"uint8 send_method\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::swarmcomm_msgs::data_buffer_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarmcomm_msgs::data_buffer_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
      stream.next(m.send_method);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct data_buffer_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarmcomm_msgs::data_buffer_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarmcomm_msgs::data_buffer_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
    s << indent << "send_method: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.send_method);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARMCOMM_MSGS_MESSAGE_DATA_BUFFER_H
