// Generated by gencpp from file swarmcomm_msgs/incoming_broadcast_data.msg
// DO NOT EDIT!


#ifndef SWARMCOMM_MSGS_MESSAGE_INCOMING_BROADCAST_DATA_H
#define SWARMCOMM_MSGS_MESSAGE_INCOMING_BROADCAST_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace swarmcomm_msgs
{
template <class ContainerAllocator>
struct incoming_broadcast_data_
{
  typedef incoming_broadcast_data_<ContainerAllocator> Type;

  incoming_broadcast_data_()
    : header()
    , remote_id(0)
    , remote_recv_time(0)
    , lps_time(0)
    , data()
    , source(0)  {
    }
  incoming_broadcast_data_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , remote_id(0)
    , remote_recv_time(0)
    , lps_time(0)
    , data(_alloc)
    , source(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _remote_id_type;
  _remote_id_type remote_id;

   typedef uint32_t _remote_recv_time_type;
  _remote_recv_time_type remote_recv_time;

   typedef uint32_t _lps_time_type;
  _lps_time_type lps_time;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _data_type;
  _data_type data;

   typedef int8_t _source_type;
  _source_type source;





  typedef boost::shared_ptr< ::swarmcomm_msgs::incoming_broadcast_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarmcomm_msgs::incoming_broadcast_data_<ContainerAllocator> const> ConstPtr;

}; // struct incoming_broadcast_data_

typedef ::swarmcomm_msgs::incoming_broadcast_data_<std::allocator<void> > incoming_broadcast_data;

typedef boost::shared_ptr< ::swarmcomm_msgs::incoming_broadcast_data > incoming_broadcast_dataPtr;
typedef boost::shared_ptr< ::swarmcomm_msgs::incoming_broadcast_data const> incoming_broadcast_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarmcomm_msgs::incoming_broadcast_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarmcomm_msgs::incoming_broadcast_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarmcomm_msgs::incoming_broadcast_data_<ContainerAllocator1> & lhs, const ::swarmcomm_msgs::incoming_broadcast_data_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.remote_id == rhs.remote_id &&
    lhs.remote_recv_time == rhs.remote_recv_time &&
    lhs.lps_time == rhs.lps_time &&
    lhs.data == rhs.data &&
    lhs.source == rhs.source;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarmcomm_msgs::incoming_broadcast_data_<ContainerAllocator1> & lhs, const ::swarmcomm_msgs::incoming_broadcast_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarmcomm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarmcomm_msgs::incoming_broadcast_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarmcomm_msgs::incoming_broadcast_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarmcomm_msgs::incoming_broadcast_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarmcomm_msgs::incoming_broadcast_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarmcomm_msgs::incoming_broadcast_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarmcomm_msgs::incoming_broadcast_data_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarmcomm_msgs::incoming_broadcast_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7fbd088099406fde7cc514736d266b32";
  }

  static const char* value(const ::swarmcomm_msgs::incoming_broadcast_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7fbd088099406fdeULL;
  static const uint64_t static_value2 = 0x7cc514736d266b32ULL;
};

template<class ContainerAllocator>
struct DataType< ::swarmcomm_msgs::incoming_broadcast_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarmcomm_msgs/incoming_broadcast_data";
  }

  static const char* value(const ::swarmcomm_msgs::incoming_broadcast_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarmcomm_msgs::incoming_broadcast_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint32 remote_id\n"
"uint32 remote_recv_time\n"
"uint32 lps_time\n"
"uint8[] data\n"
"\n"
"int8 source #0 UWB 1 WIFI\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::swarmcomm_msgs::incoming_broadcast_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarmcomm_msgs::incoming_broadcast_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.remote_id);
      stream.next(m.remote_recv_time);
      stream.next(m.lps_time);
      stream.next(m.data);
      stream.next(m.source);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct incoming_broadcast_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarmcomm_msgs::incoming_broadcast_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarmcomm_msgs::incoming_broadcast_data_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "remote_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.remote_id);
    s << indent << "remote_recv_time: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.remote_recv_time);
    s << indent << "lps_time: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.lps_time);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
    s << indent << "source: ";
    Printer<int8_t>::stream(s, indent + "  ", v.source);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARMCOMM_MSGS_MESSAGE_INCOMING_BROADCAST_DATA_H
