// Generated by gencpp from file swarmcomm_msgs/remote_uwb_info.msg
// DO NOT EDIT!


#ifndef SWARMCOMM_MSGS_MESSAGE_REMOTE_UWB_INFO_H
#define SWARMCOMM_MSGS_MESSAGE_REMOTE_UWB_INFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace swarmcomm_msgs
{
template <class ContainerAllocator>
struct remote_uwb_info_
{
  typedef remote_uwb_info_<ContainerAllocator> Type;

  remote_uwb_info_()
    : header()
    , sys_time(0)
    , remote_node_num(0)
    , self_id(0)
    , node_ids()
    , node_dis()
    , fp_rssi()
    , rx_rssi()
    , recv_distance_time()
    , active()  {
    }
  remote_uwb_info_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sys_time(0)
    , remote_node_num(0)
    , self_id(0)
    , node_ids(_alloc)
    , node_dis(_alloc)
    , fp_rssi(_alloc)
    , rx_rssi(_alloc)
    , recv_distance_time(_alloc)
    , active(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _sys_time_type;
  _sys_time_type sys_time;

   typedef uint32_t _remote_node_num_type;
  _remote_node_num_type remote_node_num;

   typedef uint32_t _self_id_type;
  _self_id_type self_id;

   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _node_ids_type;
  _node_ids_type node_ids;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _node_dis_type;
  _node_dis_type node_dis;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _fp_rssi_type;
  _fp_rssi_type fp_rssi;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _rx_rssi_type;
  _rx_rssi_type rx_rssi;

   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _recv_distance_time_type;
  _recv_distance_time_type recv_distance_time;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _active_type;
  _active_type active;





  typedef boost::shared_ptr< ::swarmcomm_msgs::remote_uwb_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarmcomm_msgs::remote_uwb_info_<ContainerAllocator> const> ConstPtr;

}; // struct remote_uwb_info_

typedef ::swarmcomm_msgs::remote_uwb_info_<std::allocator<void> > remote_uwb_info;

typedef boost::shared_ptr< ::swarmcomm_msgs::remote_uwb_info > remote_uwb_infoPtr;
typedef boost::shared_ptr< ::swarmcomm_msgs::remote_uwb_info const> remote_uwb_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarmcomm_msgs::remote_uwb_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarmcomm_msgs::remote_uwb_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarmcomm_msgs::remote_uwb_info_<ContainerAllocator1> & lhs, const ::swarmcomm_msgs::remote_uwb_info_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.sys_time == rhs.sys_time &&
    lhs.remote_node_num == rhs.remote_node_num &&
    lhs.self_id == rhs.self_id &&
    lhs.node_ids == rhs.node_ids &&
    lhs.node_dis == rhs.node_dis &&
    lhs.fp_rssi == rhs.fp_rssi &&
    lhs.rx_rssi == rhs.rx_rssi &&
    lhs.recv_distance_time == rhs.recv_distance_time &&
    lhs.active == rhs.active;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarmcomm_msgs::remote_uwb_info_<ContainerAllocator1> & lhs, const ::swarmcomm_msgs::remote_uwb_info_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarmcomm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarmcomm_msgs::remote_uwb_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarmcomm_msgs::remote_uwb_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarmcomm_msgs::remote_uwb_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarmcomm_msgs::remote_uwb_info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarmcomm_msgs::remote_uwb_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarmcomm_msgs::remote_uwb_info_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarmcomm_msgs::remote_uwb_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e25f2594fd25635dd69a8518fb143b76";
  }

  static const char* value(const ::swarmcomm_msgs::remote_uwb_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe25f2594fd25635dULL;
  static const uint64_t static_value2 = 0xd69a8518fb143b76ULL;
};

template<class ContainerAllocator>
struct DataType< ::swarmcomm_msgs::remote_uwb_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarmcomm_msgs/remote_uwb_info";
  }

  static const char* value(const ::swarmcomm_msgs::remote_uwb_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarmcomm_msgs::remote_uwb_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint32 sys_time\n"
"uint32 remote_node_num\n"
"uint32 self_id\n"
"uint32[] node_ids\n"
"float32[] node_dis\n"
"float32[] fp_rssi\n"
"float32[] rx_rssi\n"
"uint32[] recv_distance_time\n"
"bool[] active\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::swarmcomm_msgs::remote_uwb_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarmcomm_msgs::remote_uwb_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sys_time);
      stream.next(m.remote_node_num);
      stream.next(m.self_id);
      stream.next(m.node_ids);
      stream.next(m.node_dis);
      stream.next(m.fp_rssi);
      stream.next(m.rx_rssi);
      stream.next(m.recv_distance_time);
      stream.next(m.active);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct remote_uwb_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarmcomm_msgs::remote_uwb_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarmcomm_msgs::remote_uwb_info_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sys_time: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.sys_time);
    s << indent << "remote_node_num: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.remote_node_num);
    s << indent << "self_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.self_id);
    s << indent << "node_ids[]" << std::endl;
    for (size_t i = 0; i < v.node_ids.size(); ++i)
    {
      s << indent << "  node_ids[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.node_ids[i]);
    }
    s << indent << "node_dis[]" << std::endl;
    for (size_t i = 0; i < v.node_dis.size(); ++i)
    {
      s << indent << "  node_dis[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.node_dis[i]);
    }
    s << indent << "fp_rssi[]" << std::endl;
    for (size_t i = 0; i < v.fp_rssi.size(); ++i)
    {
      s << indent << "  fp_rssi[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.fp_rssi[i]);
    }
    s << indent << "rx_rssi[]" << std::endl;
    for (size_t i = 0; i < v.rx_rssi.size(); ++i)
    {
      s << indent << "  rx_rssi[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.rx_rssi[i]);
    }
    s << indent << "recv_distance_time[]" << std::endl;
    for (size_t i = 0; i < v.recv_distance_time.size(); ++i)
    {
      s << indent << "  recv_distance_time[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.recv_distance_time[i]);
    }
    s << indent << "active[]" << std::endl;
    for (size_t i = 0; i < v.active.size(); ++i)
    {
      s << indent << "  active[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.active[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARMCOMM_MSGS_MESSAGE_REMOTE_UWB_INFO_H
