// Generated by gencpp from file swarmcomm_msgs/swarm_network_status.msg
// DO NOT EDIT!


#ifndef SWARMCOMM_MSGS_MESSAGE_SWARM_NETWORK_STATUS_H
#define SWARMCOMM_MSGS_MESSAGE_SWARM_NETWORK_STATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <swarmcomm_msgs/drone_network_status.h>

namespace swarmcomm_msgs
{
template <class ContainerAllocator>
struct swarm_network_status_
{
  typedef swarm_network_status_<ContainerAllocator> Type;

  swarm_network_status_()
    : header()
    , node_ids()
    , network_status()  {
    }
  swarm_network_status_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , node_ids(_alloc)
    , network_status(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _node_ids_type;
  _node_ids_type node_ids;

   typedef std::vector< ::swarmcomm_msgs::drone_network_status_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::swarmcomm_msgs::drone_network_status_<ContainerAllocator> >> _network_status_type;
  _network_status_type network_status;





  typedef boost::shared_ptr< ::swarmcomm_msgs::swarm_network_status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarmcomm_msgs::swarm_network_status_<ContainerAllocator> const> ConstPtr;

}; // struct swarm_network_status_

typedef ::swarmcomm_msgs::swarm_network_status_<std::allocator<void> > swarm_network_status;

typedef boost::shared_ptr< ::swarmcomm_msgs::swarm_network_status > swarm_network_statusPtr;
typedef boost::shared_ptr< ::swarmcomm_msgs::swarm_network_status const> swarm_network_statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarmcomm_msgs::swarm_network_status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarmcomm_msgs::swarm_network_status_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarmcomm_msgs::swarm_network_status_<ContainerAllocator1> & lhs, const ::swarmcomm_msgs::swarm_network_status_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.node_ids == rhs.node_ids &&
    lhs.network_status == rhs.network_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarmcomm_msgs::swarm_network_status_<ContainerAllocator1> & lhs, const ::swarmcomm_msgs::swarm_network_status_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarmcomm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarmcomm_msgs::swarm_network_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarmcomm_msgs::swarm_network_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarmcomm_msgs::swarm_network_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarmcomm_msgs::swarm_network_status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarmcomm_msgs::swarm_network_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarmcomm_msgs::swarm_network_status_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarmcomm_msgs::swarm_network_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1c1c1859eb0bfda60ba46555f90ca67f";
  }

  static const char* value(const ::swarmcomm_msgs::swarm_network_status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1c1c1859eb0bfda6ULL;
  static const uint64_t static_value2 = 0x0ba46555f90ca67fULL;
};

template<class ContainerAllocator>
struct DataType< ::swarmcomm_msgs::swarm_network_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarmcomm_msgs/swarm_network_status";
  }

  static const char* value(const ::swarmcomm_msgs::swarm_network_status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarmcomm_msgs::swarm_network_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint32[] node_ids\n"
"drone_network_status[] network_status\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: swarmcomm_msgs/drone_network_status\n"
"Header header\n"
"uint32 drone_id\n"
"bool active\n"
"int32 quality\n"
"int32 bandwidth\n"
"int32 hops\n"
;
  }

  static const char* value(const ::swarmcomm_msgs::swarm_network_status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarmcomm_msgs::swarm_network_status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.node_ids);
      stream.next(m.network_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct swarm_network_status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarmcomm_msgs::swarm_network_status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarmcomm_msgs::swarm_network_status_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "node_ids[]" << std::endl;
    for (size_t i = 0; i < v.node_ids.size(); ++i)
    {
      s << indent << "  node_ids[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.node_ids[i]);
    }
    s << indent << "network_status[]" << std::endl;
    for (size_t i = 0; i < v.network_status.size(); ++i)
    {
      s << indent << "  network_status[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::swarmcomm_msgs::drone_network_status_<ContainerAllocator> >::stream(s, indent + "    ", v.network_status[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARMCOMM_MSGS_MESSAGE_SWARM_NETWORK_STATUS_H
