# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from swarm_msgs/ImageDescriptor.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class ImageDescriptor(genpy.Message):
  _md5sum = "4f5e8e454632afe4a9ed9bcee95f3cff"
  _type = "swarm_msgs/ImageDescriptor"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
int32 drone_id

float32[] feature_descriptor

geometry_msgs/Pose pose_drone
geometry_msgs/Pose camera_extrinsic

float32[] image_desc
int32 image_width
int32 image_height
uint8[] image

geometry_msgs/Point32[] landmarks_2d_norm
geometry_msgs/Point32[] landmarks_2d
geometry_msgs/Point32[] landmarks_3d
uint8[] landmarks_flag
bool prevent_adding_db

int32 direction
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Point32
# This contains the position of a point in free space(with 32 bits of precision).
# It is recommeded to use Point wherever possible instead of Point32.  
# 
# This recommendation is to promote interoperability.  
#
# This message is designed to take up less space when sending
# lots of points at once, as in the case of a PointCloud.  

float32 x
float32 y
float32 z"""
  __slots__ = ['header','drone_id','feature_descriptor','pose_drone','camera_extrinsic','image_desc','image_width','image_height','image','landmarks_2d_norm','landmarks_2d','landmarks_3d','landmarks_flag','prevent_adding_db','direction']
  _slot_types = ['std_msgs/Header','int32','float32[]','geometry_msgs/Pose','geometry_msgs/Pose','float32[]','int32','int32','uint8[]','geometry_msgs/Point32[]','geometry_msgs/Point32[]','geometry_msgs/Point32[]','uint8[]','bool','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,drone_id,feature_descriptor,pose_drone,camera_extrinsic,image_desc,image_width,image_height,image,landmarks_2d_norm,landmarks_2d,landmarks_3d,landmarks_flag,prevent_adding_db,direction

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ImageDescriptor, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.drone_id is None:
        self.drone_id = 0
      if self.feature_descriptor is None:
        self.feature_descriptor = []
      if self.pose_drone is None:
        self.pose_drone = geometry_msgs.msg.Pose()
      if self.camera_extrinsic is None:
        self.camera_extrinsic = geometry_msgs.msg.Pose()
      if self.image_desc is None:
        self.image_desc = []
      if self.image_width is None:
        self.image_width = 0
      if self.image_height is None:
        self.image_height = 0
      if self.image is None:
        self.image = b''
      if self.landmarks_2d_norm is None:
        self.landmarks_2d_norm = []
      if self.landmarks_2d is None:
        self.landmarks_2d = []
      if self.landmarks_3d is None:
        self.landmarks_3d = []
      if self.landmarks_flag is None:
        self.landmarks_flag = b''
      if self.prevent_adding_db is None:
        self.prevent_adding_db = False
      if self.direction is None:
        self.direction = 0
    else:
      self.header = std_msgs.msg.Header()
      self.drone_id = 0
      self.feature_descriptor = []
      self.pose_drone = geometry_msgs.msg.Pose()
      self.camera_extrinsic = geometry_msgs.msg.Pose()
      self.image_desc = []
      self.image_width = 0
      self.image_height = 0
      self.image = b''
      self.landmarks_2d_norm = []
      self.landmarks_2d = []
      self.landmarks_3d = []
      self.landmarks_flag = b''
      self.prevent_adding_db = False
      self.direction = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.drone_id
      buff.write(_get_struct_i().pack(_x))
      length = len(self.feature_descriptor)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.feature_descriptor))
      _x = self
      buff.write(_get_struct_14d().pack(_x.pose_drone.position.x, _x.pose_drone.position.y, _x.pose_drone.position.z, _x.pose_drone.orientation.x, _x.pose_drone.orientation.y, _x.pose_drone.orientation.z, _x.pose_drone.orientation.w, _x.camera_extrinsic.position.x, _x.camera_extrinsic.position.y, _x.camera_extrinsic.position.z, _x.camera_extrinsic.orientation.x, _x.camera_extrinsic.orientation.y, _x.camera_extrinsic.orientation.z, _x.camera_extrinsic.orientation.w))
      length = len(self.image_desc)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.image_desc))
      _x = self
      buff.write(_get_struct_2i().pack(_x.image_width, _x.image_height))
      _x = self.image
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.landmarks_2d_norm)
      buff.write(_struct_I.pack(length))
      for val1 in self.landmarks_2d_norm:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      length = len(self.landmarks_2d)
      buff.write(_struct_I.pack(length))
      for val1 in self.landmarks_2d:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      length = len(self.landmarks_3d)
      buff.write(_struct_I.pack(length))
      for val1 in self.landmarks_3d:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      _x = self.landmarks_flag
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_Bi().pack(_x.prevent_adding_db, _x.direction))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pose_drone is None:
        self.pose_drone = geometry_msgs.msg.Pose()
      if self.camera_extrinsic is None:
        self.camera_extrinsic = geometry_msgs.msg.Pose()
      if self.landmarks_2d_norm is None:
        self.landmarks_2d_norm = None
      if self.landmarks_2d is None:
        self.landmarks_2d = None
      if self.landmarks_3d is None:
        self.landmarks_3d = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (self.drone_id,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.feature_descriptor = s.unpack(str[start:end])
      _x = self
      start = end
      end += 112
      (_x.pose_drone.position.x, _x.pose_drone.position.y, _x.pose_drone.position.z, _x.pose_drone.orientation.x, _x.pose_drone.orientation.y, _x.pose_drone.orientation.z, _x.pose_drone.orientation.w, _x.camera_extrinsic.position.x, _x.camera_extrinsic.position.y, _x.camera_extrinsic.position.z, _x.camera_extrinsic.orientation.x, _x.camera_extrinsic.orientation.y, _x.camera_extrinsic.orientation.z, _x.camera_extrinsic.orientation.w,) = _get_struct_14d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.image_desc = s.unpack(str[start:end])
      _x = self
      start = end
      end += 8
      (_x.image_width, _x.image_height,) = _get_struct_2i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.image = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.landmarks_2d_norm = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point32()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.landmarks_2d_norm.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.landmarks_2d = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point32()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.landmarks_2d.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.landmarks_3d = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point32()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.landmarks_3d.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.landmarks_flag = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.prevent_adding_db, _x.direction,) = _get_struct_Bi().unpack(str[start:end])
      self.prevent_adding_db = bool(self.prevent_adding_db)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.drone_id
      buff.write(_get_struct_i().pack(_x))
      length = len(self.feature_descriptor)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.feature_descriptor.tostring())
      _x = self
      buff.write(_get_struct_14d().pack(_x.pose_drone.position.x, _x.pose_drone.position.y, _x.pose_drone.position.z, _x.pose_drone.orientation.x, _x.pose_drone.orientation.y, _x.pose_drone.orientation.z, _x.pose_drone.orientation.w, _x.camera_extrinsic.position.x, _x.camera_extrinsic.position.y, _x.camera_extrinsic.position.z, _x.camera_extrinsic.orientation.x, _x.camera_extrinsic.orientation.y, _x.camera_extrinsic.orientation.z, _x.camera_extrinsic.orientation.w))
      length = len(self.image_desc)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.image_desc.tostring())
      _x = self
      buff.write(_get_struct_2i().pack(_x.image_width, _x.image_height))
      _x = self.image
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.landmarks_2d_norm)
      buff.write(_struct_I.pack(length))
      for val1 in self.landmarks_2d_norm:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      length = len(self.landmarks_2d)
      buff.write(_struct_I.pack(length))
      for val1 in self.landmarks_2d:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      length = len(self.landmarks_3d)
      buff.write(_struct_I.pack(length))
      for val1 in self.landmarks_3d:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      _x = self.landmarks_flag
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_Bi().pack(_x.prevent_adding_db, _x.direction))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pose_drone is None:
        self.pose_drone = geometry_msgs.msg.Pose()
      if self.camera_extrinsic is None:
        self.camera_extrinsic = geometry_msgs.msg.Pose()
      if self.landmarks_2d_norm is None:
        self.landmarks_2d_norm = None
      if self.landmarks_2d is None:
        self.landmarks_2d = None
      if self.landmarks_3d is None:
        self.landmarks_3d = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (self.drone_id,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.feature_descriptor = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 112
      (_x.pose_drone.position.x, _x.pose_drone.position.y, _x.pose_drone.position.z, _x.pose_drone.orientation.x, _x.pose_drone.orientation.y, _x.pose_drone.orientation.z, _x.pose_drone.orientation.w, _x.camera_extrinsic.position.x, _x.camera_extrinsic.position.y, _x.camera_extrinsic.position.z, _x.camera_extrinsic.orientation.x, _x.camera_extrinsic.orientation.y, _x.camera_extrinsic.orientation.z, _x.camera_extrinsic.orientation.w,) = _get_struct_14d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.image_desc = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 8
      (_x.image_width, _x.image_height,) = _get_struct_2i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.image = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.landmarks_2d_norm = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point32()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.landmarks_2d_norm.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.landmarks_2d = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point32()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.landmarks_2d.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.landmarks_3d = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point32()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.landmarks_3d.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.landmarks_flag = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.prevent_adding_db, _x.direction,) = _get_struct_Bi().unpack(str[start:end])
      self.prevent_adding_db = bool(self.prevent_adding_db)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_14d = None
def _get_struct_14d():
    global _struct_14d
    if _struct_14d is None:
        _struct_14d = struct.Struct("<14d")
    return _struct_14d
_struct_2i = None
def _get_struct_2i():
    global _struct_2i
    if _struct_2i is None:
        _struct_2i = struct.Struct("<2i")
    return _struct_2i
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_Bi = None
def _get_struct_Bi():
    global _struct_Bi
    if _struct_Bi is None:
        _struct_Bi = struct.Struct("<Bi")
    return _struct_Bi
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
