# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from swarm_msgs/node_detected_xyzyaw.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class node_detected_xyzyaw(genpy.Message):
  _md5sum = "153d8a388ec70ddfe9950d5a9c645eda"
  _type = "swarm_msgs/node_detected_xyzyaw"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
int64 id
int32 self_drone_id
int32 remote_drone_id
geometry_msgs/Point dpos
geometry_msgs/Point dpos_std

float64 dyaw
float64 dyaw_cov
bool enable_scale
bool is_yaw_valid
float64 probaility
float64 inv_dep

geometry_msgs/Pose local_pose_self #Here is camera pose, not IMU pose.
geometry_msgs/Pose local_pose_remote

geometry_msgs/Pose camera_extrinsic
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['header','id','self_drone_id','remote_drone_id','dpos','dpos_std','dyaw','dyaw_cov','enable_scale','is_yaw_valid','probaility','inv_dep','local_pose_self','local_pose_remote','camera_extrinsic']
  _slot_types = ['std_msgs/Header','int64','int32','int32','geometry_msgs/Point','geometry_msgs/Point','float64','float64','bool','bool','float64','float64','geometry_msgs/Pose','geometry_msgs/Pose','geometry_msgs/Pose']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,id,self_drone_id,remote_drone_id,dpos,dpos_std,dyaw,dyaw_cov,enable_scale,is_yaw_valid,probaility,inv_dep,local_pose_self,local_pose_remote,camera_extrinsic

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(node_detected_xyzyaw, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.id is None:
        self.id = 0
      if self.self_drone_id is None:
        self.self_drone_id = 0
      if self.remote_drone_id is None:
        self.remote_drone_id = 0
      if self.dpos is None:
        self.dpos = geometry_msgs.msg.Point()
      if self.dpos_std is None:
        self.dpos_std = geometry_msgs.msg.Point()
      if self.dyaw is None:
        self.dyaw = 0.
      if self.dyaw_cov is None:
        self.dyaw_cov = 0.
      if self.enable_scale is None:
        self.enable_scale = False
      if self.is_yaw_valid is None:
        self.is_yaw_valid = False
      if self.probaility is None:
        self.probaility = 0.
      if self.inv_dep is None:
        self.inv_dep = 0.
      if self.local_pose_self is None:
        self.local_pose_self = geometry_msgs.msg.Pose()
      if self.local_pose_remote is None:
        self.local_pose_remote = geometry_msgs.msg.Pose()
      if self.camera_extrinsic is None:
        self.camera_extrinsic = geometry_msgs.msg.Pose()
    else:
      self.header = std_msgs.msg.Header()
      self.id = 0
      self.self_drone_id = 0
      self.remote_drone_id = 0
      self.dpos = geometry_msgs.msg.Point()
      self.dpos_std = geometry_msgs.msg.Point()
      self.dyaw = 0.
      self.dyaw_cov = 0.
      self.enable_scale = False
      self.is_yaw_valid = False
      self.probaility = 0.
      self.inv_dep = 0.
      self.local_pose_self = geometry_msgs.msg.Pose()
      self.local_pose_remote = geometry_msgs.msg.Pose()
      self.camera_extrinsic = geometry_msgs.msg.Pose()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_q2i8d2B23d().pack(_x.id, _x.self_drone_id, _x.remote_drone_id, _x.dpos.x, _x.dpos.y, _x.dpos.z, _x.dpos_std.x, _x.dpos_std.y, _x.dpos_std.z, _x.dyaw, _x.dyaw_cov, _x.enable_scale, _x.is_yaw_valid, _x.probaility, _x.inv_dep, _x.local_pose_self.position.x, _x.local_pose_self.position.y, _x.local_pose_self.position.z, _x.local_pose_self.orientation.x, _x.local_pose_self.orientation.y, _x.local_pose_self.orientation.z, _x.local_pose_self.orientation.w, _x.local_pose_remote.position.x, _x.local_pose_remote.position.y, _x.local_pose_remote.position.z, _x.local_pose_remote.orientation.x, _x.local_pose_remote.orientation.y, _x.local_pose_remote.orientation.z, _x.local_pose_remote.orientation.w, _x.camera_extrinsic.position.x, _x.camera_extrinsic.position.y, _x.camera_extrinsic.position.z, _x.camera_extrinsic.orientation.x, _x.camera_extrinsic.orientation.y, _x.camera_extrinsic.orientation.z, _x.camera_extrinsic.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.dpos is None:
        self.dpos = geometry_msgs.msg.Point()
      if self.dpos_std is None:
        self.dpos_std = geometry_msgs.msg.Point()
      if self.local_pose_self is None:
        self.local_pose_self = geometry_msgs.msg.Pose()
      if self.local_pose_remote is None:
        self.local_pose_remote = geometry_msgs.msg.Pose()
      if self.camera_extrinsic is None:
        self.camera_extrinsic = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 266
      (_x.id, _x.self_drone_id, _x.remote_drone_id, _x.dpos.x, _x.dpos.y, _x.dpos.z, _x.dpos_std.x, _x.dpos_std.y, _x.dpos_std.z, _x.dyaw, _x.dyaw_cov, _x.enable_scale, _x.is_yaw_valid, _x.probaility, _x.inv_dep, _x.local_pose_self.position.x, _x.local_pose_self.position.y, _x.local_pose_self.position.z, _x.local_pose_self.orientation.x, _x.local_pose_self.orientation.y, _x.local_pose_self.orientation.z, _x.local_pose_self.orientation.w, _x.local_pose_remote.position.x, _x.local_pose_remote.position.y, _x.local_pose_remote.position.z, _x.local_pose_remote.orientation.x, _x.local_pose_remote.orientation.y, _x.local_pose_remote.orientation.z, _x.local_pose_remote.orientation.w, _x.camera_extrinsic.position.x, _x.camera_extrinsic.position.y, _x.camera_extrinsic.position.z, _x.camera_extrinsic.orientation.x, _x.camera_extrinsic.orientation.y, _x.camera_extrinsic.orientation.z, _x.camera_extrinsic.orientation.w,) = _get_struct_q2i8d2B23d().unpack(str[start:end])
      self.enable_scale = bool(self.enable_scale)
      self.is_yaw_valid = bool(self.is_yaw_valid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_q2i8d2B23d().pack(_x.id, _x.self_drone_id, _x.remote_drone_id, _x.dpos.x, _x.dpos.y, _x.dpos.z, _x.dpos_std.x, _x.dpos_std.y, _x.dpos_std.z, _x.dyaw, _x.dyaw_cov, _x.enable_scale, _x.is_yaw_valid, _x.probaility, _x.inv_dep, _x.local_pose_self.position.x, _x.local_pose_self.position.y, _x.local_pose_self.position.z, _x.local_pose_self.orientation.x, _x.local_pose_self.orientation.y, _x.local_pose_self.orientation.z, _x.local_pose_self.orientation.w, _x.local_pose_remote.position.x, _x.local_pose_remote.position.y, _x.local_pose_remote.position.z, _x.local_pose_remote.orientation.x, _x.local_pose_remote.orientation.y, _x.local_pose_remote.orientation.z, _x.local_pose_remote.orientation.w, _x.camera_extrinsic.position.x, _x.camera_extrinsic.position.y, _x.camera_extrinsic.position.z, _x.camera_extrinsic.orientation.x, _x.camera_extrinsic.orientation.y, _x.camera_extrinsic.orientation.z, _x.camera_extrinsic.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.dpos is None:
        self.dpos = geometry_msgs.msg.Point()
      if self.dpos_std is None:
        self.dpos_std = geometry_msgs.msg.Point()
      if self.local_pose_self is None:
        self.local_pose_self = geometry_msgs.msg.Pose()
      if self.local_pose_remote is None:
        self.local_pose_remote = geometry_msgs.msg.Pose()
      if self.camera_extrinsic is None:
        self.camera_extrinsic = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 266
      (_x.id, _x.self_drone_id, _x.remote_drone_id, _x.dpos.x, _x.dpos.y, _x.dpos.z, _x.dpos_std.x, _x.dpos_std.y, _x.dpos_std.z, _x.dyaw, _x.dyaw_cov, _x.enable_scale, _x.is_yaw_valid, _x.probaility, _x.inv_dep, _x.local_pose_self.position.x, _x.local_pose_self.position.y, _x.local_pose_self.position.z, _x.local_pose_self.orientation.x, _x.local_pose_self.orientation.y, _x.local_pose_self.orientation.z, _x.local_pose_self.orientation.w, _x.local_pose_remote.position.x, _x.local_pose_remote.position.y, _x.local_pose_remote.position.z, _x.local_pose_remote.orientation.x, _x.local_pose_remote.orientation.y, _x.local_pose_remote.orientation.z, _x.local_pose_remote.orientation.w, _x.camera_extrinsic.position.x, _x.camera_extrinsic.position.y, _x.camera_extrinsic.position.z, _x.camera_extrinsic.orientation.x, _x.camera_extrinsic.orientation.y, _x.camera_extrinsic.orientation.z, _x.camera_extrinsic.orientation.w,) = _get_struct_q2i8d2B23d().unpack(str[start:end])
      self.enable_scale = bool(self.enable_scale)
      self.is_yaw_valid = bool(self.is_yaw_valid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_q2i8d2B23d = None
def _get_struct_q2i8d2B23d():
    global _struct_q2i8d2B23d
    if _struct_q2i8d2B23d is None:
        _struct_q2i8d2B23d = struct.Struct("<q2i8d2B23d")
    return _struct_q2i8d2B23d
