# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from swarm_msgs/node_detected.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class node_detected(genpy.Message):
  _md5sum = "d83c2e1345fc81767f3cd9584b06399b"
  _type = "swarm_msgs/node_detected"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
int64 id
int32 self_drone_id
int32 remote_drone_id
geometry_msgs/PoseWithCovariance relative_pose #If 2d detect, gives x=1
bool is_2d_detect
bool is_yaw_valid
float64 probaility
geometry_msgs/Pose local_pose_self
geometry_msgs/Pose local_pose_remote
bool dof_4
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/PoseWithCovariance
# This represents a pose in free space with uncertainty.

Pose pose

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['header','id','self_drone_id','remote_drone_id','relative_pose','is_2d_detect','is_yaw_valid','probaility','local_pose_self','local_pose_remote','dof_4']
  _slot_types = ['std_msgs/Header','int64','int32','int32','geometry_msgs/PoseWithCovariance','bool','bool','float64','geometry_msgs/Pose','geometry_msgs/Pose','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,id,self_drone_id,remote_drone_id,relative_pose,is_2d_detect,is_yaw_valid,probaility,local_pose_self,local_pose_remote,dof_4

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(node_detected, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.id is None:
        self.id = 0
      if self.self_drone_id is None:
        self.self_drone_id = 0
      if self.remote_drone_id is None:
        self.remote_drone_id = 0
      if self.relative_pose is None:
        self.relative_pose = geometry_msgs.msg.PoseWithCovariance()
      if self.is_2d_detect is None:
        self.is_2d_detect = False
      if self.is_yaw_valid is None:
        self.is_yaw_valid = False
      if self.probaility is None:
        self.probaility = 0.
      if self.local_pose_self is None:
        self.local_pose_self = geometry_msgs.msg.Pose()
      if self.local_pose_remote is None:
        self.local_pose_remote = geometry_msgs.msg.Pose()
      if self.dof_4 is None:
        self.dof_4 = False
    else:
      self.header = std_msgs.msg.Header()
      self.id = 0
      self.self_drone_id = 0
      self.remote_drone_id = 0
      self.relative_pose = geometry_msgs.msg.PoseWithCovariance()
      self.is_2d_detect = False
      self.is_yaw_valid = False
      self.probaility = 0.
      self.local_pose_self = geometry_msgs.msg.Pose()
      self.local_pose_remote = geometry_msgs.msg.Pose()
      self.dof_4 = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_q2i7d().pack(_x.id, _x.self_drone_id, _x.remote_drone_id, _x.relative_pose.pose.position.x, _x.relative_pose.pose.position.y, _x.relative_pose.pose.position.z, _x.relative_pose.pose.orientation.x, _x.relative_pose.pose.orientation.y, _x.relative_pose.pose.orientation.z, _x.relative_pose.pose.orientation.w))
      buff.write(_get_struct_36d().pack(*self.relative_pose.covariance))
      _x = self
      buff.write(_get_struct_2B15dB().pack(_x.is_2d_detect, _x.is_yaw_valid, _x.probaility, _x.local_pose_self.position.x, _x.local_pose_self.position.y, _x.local_pose_self.position.z, _x.local_pose_self.orientation.x, _x.local_pose_self.orientation.y, _x.local_pose_self.orientation.z, _x.local_pose_self.orientation.w, _x.local_pose_remote.position.x, _x.local_pose_remote.position.y, _x.local_pose_remote.position.z, _x.local_pose_remote.orientation.x, _x.local_pose_remote.orientation.y, _x.local_pose_remote.orientation.z, _x.local_pose_remote.orientation.w, _x.dof_4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.relative_pose is None:
        self.relative_pose = geometry_msgs.msg.PoseWithCovariance()
      if self.local_pose_self is None:
        self.local_pose_self = geometry_msgs.msg.Pose()
      if self.local_pose_remote is None:
        self.local_pose_remote = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 72
      (_x.id, _x.self_drone_id, _x.remote_drone_id, _x.relative_pose.pose.position.x, _x.relative_pose.pose.position.y, _x.relative_pose.pose.position.z, _x.relative_pose.pose.orientation.x, _x.relative_pose.pose.orientation.y, _x.relative_pose.pose.orientation.z, _x.relative_pose.pose.orientation.w,) = _get_struct_q2i7d().unpack(str[start:end])
      start = end
      end += 288
      self.relative_pose.covariance = _get_struct_36d().unpack(str[start:end])
      _x = self
      start = end
      end += 123
      (_x.is_2d_detect, _x.is_yaw_valid, _x.probaility, _x.local_pose_self.position.x, _x.local_pose_self.position.y, _x.local_pose_self.position.z, _x.local_pose_self.orientation.x, _x.local_pose_self.orientation.y, _x.local_pose_self.orientation.z, _x.local_pose_self.orientation.w, _x.local_pose_remote.position.x, _x.local_pose_remote.position.y, _x.local_pose_remote.position.z, _x.local_pose_remote.orientation.x, _x.local_pose_remote.orientation.y, _x.local_pose_remote.orientation.z, _x.local_pose_remote.orientation.w, _x.dof_4,) = _get_struct_2B15dB().unpack(str[start:end])
      self.is_2d_detect = bool(self.is_2d_detect)
      self.is_yaw_valid = bool(self.is_yaw_valid)
      self.dof_4 = bool(self.dof_4)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_q2i7d().pack(_x.id, _x.self_drone_id, _x.remote_drone_id, _x.relative_pose.pose.position.x, _x.relative_pose.pose.position.y, _x.relative_pose.pose.position.z, _x.relative_pose.pose.orientation.x, _x.relative_pose.pose.orientation.y, _x.relative_pose.pose.orientation.z, _x.relative_pose.pose.orientation.w))
      buff.write(self.relative_pose.covariance.tostring())
      _x = self
      buff.write(_get_struct_2B15dB().pack(_x.is_2d_detect, _x.is_yaw_valid, _x.probaility, _x.local_pose_self.position.x, _x.local_pose_self.position.y, _x.local_pose_self.position.z, _x.local_pose_self.orientation.x, _x.local_pose_self.orientation.y, _x.local_pose_self.orientation.z, _x.local_pose_self.orientation.w, _x.local_pose_remote.position.x, _x.local_pose_remote.position.y, _x.local_pose_remote.position.z, _x.local_pose_remote.orientation.x, _x.local_pose_remote.orientation.y, _x.local_pose_remote.orientation.z, _x.local_pose_remote.orientation.w, _x.dof_4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.relative_pose is None:
        self.relative_pose = geometry_msgs.msg.PoseWithCovariance()
      if self.local_pose_self is None:
        self.local_pose_self = geometry_msgs.msg.Pose()
      if self.local_pose_remote is None:
        self.local_pose_remote = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 72
      (_x.id, _x.self_drone_id, _x.remote_drone_id, _x.relative_pose.pose.position.x, _x.relative_pose.pose.position.y, _x.relative_pose.pose.position.z, _x.relative_pose.pose.orientation.x, _x.relative_pose.pose.orientation.y, _x.relative_pose.pose.orientation.z, _x.relative_pose.pose.orientation.w,) = _get_struct_q2i7d().unpack(str[start:end])
      start = end
      end += 288
      self.relative_pose.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      _x = self
      start = end
      end += 123
      (_x.is_2d_detect, _x.is_yaw_valid, _x.probaility, _x.local_pose_self.position.x, _x.local_pose_self.position.y, _x.local_pose_self.position.z, _x.local_pose_self.orientation.x, _x.local_pose_self.orientation.y, _x.local_pose_self.orientation.z, _x.local_pose_self.orientation.w, _x.local_pose_remote.position.x, _x.local_pose_remote.position.y, _x.local_pose_remote.position.z, _x.local_pose_remote.orientation.x, _x.local_pose_remote.orientation.y, _x.local_pose_remote.orientation.z, _x.local_pose_remote.orientation.w, _x.dof_4,) = _get_struct_2B15dB().unpack(str[start:end])
      self.is_2d_detect = bool(self.is_2d_detect)
      self.is_yaw_valid = bool(self.is_yaw_valid)
      self.dof_4 = bool(self.dof_4)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B15dB = None
def _get_struct_2B15dB():
    global _struct_2B15dB
    if _struct_2B15dB is None:
        _struct_2B15dB = struct.Struct("<2B15dB")
    return _struct_2B15dB
_struct_36d = None
def _get_struct_36d():
    global _struct_36d
    if _struct_36d is None:
        _struct_36d = struct.Struct("<36d")
    return _struct_36d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_q2i7d = None
def _get_struct_q2i7d():
    global _struct_q2i7d
    if _struct_q2i7d is None:
        _struct_q2i7d = struct.Struct("<q2i7d")
    return _struct_q2i7d
