# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from swarm_msgs/swarm_frame.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg
import swarm_msgs.msg

class swarm_frame(genpy.Message):
  _md5sum = "04c8bdaacf2ca38f8b270c8aadec114d"
  _type = "swarm_msgs/swarm_frame"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
node_frame[] node_frames
int32 self_id
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: swarm_msgs/node_frame
Header header
int32 drone_id #This is drone ID!!!
uint64 keyframe_id

geometry_msgs/Point position
geometry_msgs/Point velocity
float32 yaw
float32 pitch
float32 roll
geometry_msgs/Quaternion quat

bool vo_available
int32[] dismap_ids
float64[] dismap_dists
node_detected_xyzyaw[] detected_xyzyaws
node_detected[] detected
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: swarm_msgs/node_detected_xyzyaw
Header header
int64 id
int32 self_drone_id
int32 remote_drone_id
geometry_msgs/Point dpos
geometry_msgs/Point dpos_std

float64 dyaw
float64 dyaw_cov
bool enable_scale
bool is_yaw_valid
float64 probaility
float64 inv_dep

geometry_msgs/Pose local_pose_self #Here is camera pose, not IMU pose.
geometry_msgs/Pose local_pose_remote

geometry_msgs/Pose camera_extrinsic
================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: swarm_msgs/node_detected
Header header
int64 id
int32 self_drone_id
int32 remote_drone_id
geometry_msgs/PoseWithCovariance relative_pose #If 2d detect, gives x=1
bool is_2d_detect
bool is_yaw_valid
float64 probaility
geometry_msgs/Pose local_pose_self
geometry_msgs/Pose local_pose_remote
bool dof_4
================================================================================
MSG: geometry_msgs/PoseWithCovariance
# This represents a pose in free space with uncertainty.

Pose pose

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance
"""
  __slots__ = ['header','node_frames','self_id']
  _slot_types = ['std_msgs/Header','swarm_msgs/node_frame[]','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,node_frames,self_id

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(swarm_frame, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.node_frames is None:
        self.node_frames = []
      if self.self_id is None:
        self.self_id = 0
    else:
      self.header = std_msgs.msg.Header()
      self.node_frames = []
      self.self_id = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.node_frames)
      buff.write(_struct_I.pack(length))
      for val1 in self.node_frames:
        _v1 = val1.header
        _x = _v1.seq
        buff.write(_get_struct_I().pack(_x))
        _v2 = _v1.stamp
        _x = _v2
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v1.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_iQ().pack(_x.drone_id, _x.keyframe_id))
        _v3 = val1.position
        _x = _v3
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v4 = val1.velocity
        _x = _v4
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1
        buff.write(_get_struct_3f().pack(_x.yaw, _x.pitch, _x.roll))
        _v5 = val1.quat
        _x = _v5
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
        _x = val1.vo_available
        buff.write(_get_struct_B().pack(_x))
        length = len(val1.dismap_ids)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(struct.Struct(pattern).pack(*val1.dismap_ids))
        length = len(val1.dismap_dists)
        buff.write(_struct_I.pack(length))
        pattern = '<%sd'%length
        buff.write(struct.Struct(pattern).pack(*val1.dismap_dists))
        length = len(val1.detected_xyzyaws)
        buff.write(_struct_I.pack(length))
        for val2 in val1.detected_xyzyaws:
          _v6 = val2.header
          _x = _v6.seq
          buff.write(_get_struct_I().pack(_x))
          _v7 = _v6.stamp
          _x = _v7
          buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
          _x = _v6.frame_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2
          buff.write(_get_struct_q2i().pack(_x.id, _x.self_drone_id, _x.remote_drone_id))
          _v8 = val2.dpos
          _x = _v8
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v9 = val2.dpos_std
          _x = _v9
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _x = val2
          buff.write(_get_struct_2d2B2d().pack(_x.dyaw, _x.dyaw_cov, _x.enable_scale, _x.is_yaw_valid, _x.probaility, _x.inv_dep))
          _v10 = val2.local_pose_self
          _v11 = _v10.position
          _x = _v11
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v12 = _v10.orientation
          _x = _v12
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
          _v13 = val2.local_pose_remote
          _v14 = _v13.position
          _x = _v14
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v15 = _v13.orientation
          _x = _v15
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
          _v16 = val2.camera_extrinsic
          _v17 = _v16.position
          _x = _v17
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v18 = _v16.orientation
          _x = _v18
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
        length = len(val1.detected)
        buff.write(_struct_I.pack(length))
        for val2 in val1.detected:
          _v19 = val2.header
          _x = _v19.seq
          buff.write(_get_struct_I().pack(_x))
          _v20 = _v19.stamp
          _x = _v20
          buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
          _x = _v19.frame_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2
          buff.write(_get_struct_q2i().pack(_x.id, _x.self_drone_id, _x.remote_drone_id))
          _v21 = val2.relative_pose
          _v22 = _v21.pose
          _v23 = _v22.position
          _x = _v23
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v24 = _v22.orientation
          _x = _v24
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
          buff.write(_get_struct_36d().pack(*_v21.covariance))
          _x = val2
          buff.write(_get_struct_2Bd().pack(_x.is_2d_detect, _x.is_yaw_valid, _x.probaility))
          _v25 = val2.local_pose_self
          _v26 = _v25.position
          _x = _v26
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v27 = _v25.orientation
          _x = _v27
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
          _v28 = val2.local_pose_remote
          _v29 = _v28.position
          _x = _v29
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v30 = _v28.orientation
          _x = _v30
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
          _x = val2.dof_4
          buff.write(_get_struct_B().pack(_x))
      _x = self.self_id
      buff.write(_get_struct_i().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.node_frames is None:
        self.node_frames = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.node_frames = []
      for i in range(0, length):
        val1 = swarm_msgs.msg.node_frame()
        _v31 = val1.header
        start = end
        end += 4
        (_v31.seq,) = _get_struct_I().unpack(str[start:end])
        _v32 = _v31.stamp
        _x = _v32
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v31.frame_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v31.frame_id = str[start:end]
        _x = val1
        start = end
        end += 12
        (_x.drone_id, _x.keyframe_id,) = _get_struct_iQ().unpack(str[start:end])
        _v33 = val1.position
        _x = _v33
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v34 = val1.velocity
        _x = _v34
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _x = val1
        start = end
        end += 12
        (_x.yaw, _x.pitch, _x.roll,) = _get_struct_3f().unpack(str[start:end])
        _v35 = val1.quat
        _x = _v35
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        start = end
        end += 1
        (val1.vo_available,) = _get_struct_B().unpack(str[start:end])
        val1.vo_available = bool(val1.vo_available)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.dismap_ids = s.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sd'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.dismap_dists = s.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.detected_xyzyaws = []
        for i in range(0, length):
          val2 = swarm_msgs.msg.node_detected_xyzyaw()
          _v36 = val2.header
          start = end
          end += 4
          (_v36.seq,) = _get_struct_I().unpack(str[start:end])
          _v37 = _v36.stamp
          _x = _v37
          start = end
          end += 8
          (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            _v36.frame_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            _v36.frame_id = str[start:end]
          _x = val2
          start = end
          end += 16
          (_x.id, _x.self_drone_id, _x.remote_drone_id,) = _get_struct_q2i().unpack(str[start:end])
          _v38 = val2.dpos
          _x = _v38
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v39 = val2.dpos_std
          _x = _v39
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _x = val2
          start = end
          end += 34
          (_x.dyaw, _x.dyaw_cov, _x.enable_scale, _x.is_yaw_valid, _x.probaility, _x.inv_dep,) = _get_struct_2d2B2d().unpack(str[start:end])
          val2.enable_scale = bool(val2.enable_scale)
          val2.is_yaw_valid = bool(val2.is_yaw_valid)
          _v40 = val2.local_pose_self
          _v41 = _v40.position
          _x = _v41
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v42 = _v40.orientation
          _x = _v42
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          _v43 = val2.local_pose_remote
          _v44 = _v43.position
          _x = _v44
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v45 = _v43.orientation
          _x = _v45
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          _v46 = val2.camera_extrinsic
          _v47 = _v46.position
          _x = _v47
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v48 = _v46.orientation
          _x = _v48
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          val1.detected_xyzyaws.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.detected = []
        for i in range(0, length):
          val2 = swarm_msgs.msg.node_detected()
          _v49 = val2.header
          start = end
          end += 4
          (_v49.seq,) = _get_struct_I().unpack(str[start:end])
          _v50 = _v49.stamp
          _x = _v50
          start = end
          end += 8
          (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            _v49.frame_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            _v49.frame_id = str[start:end]
          _x = val2
          start = end
          end += 16
          (_x.id, _x.self_drone_id, _x.remote_drone_id,) = _get_struct_q2i().unpack(str[start:end])
          _v51 = val2.relative_pose
          _v52 = _v51.pose
          _v53 = _v52.position
          _x = _v53
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v54 = _v52.orientation
          _x = _v54
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          start = end
          end += 288
          _v51.covariance = _get_struct_36d().unpack(str[start:end])
          _x = val2
          start = end
          end += 10
          (_x.is_2d_detect, _x.is_yaw_valid, _x.probaility,) = _get_struct_2Bd().unpack(str[start:end])
          val2.is_2d_detect = bool(val2.is_2d_detect)
          val2.is_yaw_valid = bool(val2.is_yaw_valid)
          _v55 = val2.local_pose_self
          _v56 = _v55.position
          _x = _v56
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v57 = _v55.orientation
          _x = _v57
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          _v58 = val2.local_pose_remote
          _v59 = _v58.position
          _x = _v59
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v60 = _v58.orientation
          _x = _v60
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          start = end
          end += 1
          (val2.dof_4,) = _get_struct_B().unpack(str[start:end])
          val2.dof_4 = bool(val2.dof_4)
          val1.detected.append(val2)
        self.node_frames.append(val1)
      start = end
      end += 4
      (self.self_id,) = _get_struct_i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.node_frames)
      buff.write(_struct_I.pack(length))
      for val1 in self.node_frames:
        _v61 = val1.header
        _x = _v61.seq
        buff.write(_get_struct_I().pack(_x))
        _v62 = _v61.stamp
        _x = _v62
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v61.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_iQ().pack(_x.drone_id, _x.keyframe_id))
        _v63 = val1.position
        _x = _v63
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v64 = val1.velocity
        _x = _v64
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1
        buff.write(_get_struct_3f().pack(_x.yaw, _x.pitch, _x.roll))
        _v65 = val1.quat
        _x = _v65
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
        _x = val1.vo_available
        buff.write(_get_struct_B().pack(_x))
        length = len(val1.dismap_ids)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(val1.dismap_ids.tostring())
        length = len(val1.dismap_dists)
        buff.write(_struct_I.pack(length))
        pattern = '<%sd'%length
        buff.write(val1.dismap_dists.tostring())
        length = len(val1.detected_xyzyaws)
        buff.write(_struct_I.pack(length))
        for val2 in val1.detected_xyzyaws:
          _v66 = val2.header
          _x = _v66.seq
          buff.write(_get_struct_I().pack(_x))
          _v67 = _v66.stamp
          _x = _v67
          buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
          _x = _v66.frame_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2
          buff.write(_get_struct_q2i().pack(_x.id, _x.self_drone_id, _x.remote_drone_id))
          _v68 = val2.dpos
          _x = _v68
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v69 = val2.dpos_std
          _x = _v69
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _x = val2
          buff.write(_get_struct_2d2B2d().pack(_x.dyaw, _x.dyaw_cov, _x.enable_scale, _x.is_yaw_valid, _x.probaility, _x.inv_dep))
          _v70 = val2.local_pose_self
          _v71 = _v70.position
          _x = _v71
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v72 = _v70.orientation
          _x = _v72
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
          _v73 = val2.local_pose_remote
          _v74 = _v73.position
          _x = _v74
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v75 = _v73.orientation
          _x = _v75
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
          _v76 = val2.camera_extrinsic
          _v77 = _v76.position
          _x = _v77
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v78 = _v76.orientation
          _x = _v78
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
        length = len(val1.detected)
        buff.write(_struct_I.pack(length))
        for val2 in val1.detected:
          _v79 = val2.header
          _x = _v79.seq
          buff.write(_get_struct_I().pack(_x))
          _v80 = _v79.stamp
          _x = _v80
          buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
          _x = _v79.frame_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2
          buff.write(_get_struct_q2i().pack(_x.id, _x.self_drone_id, _x.remote_drone_id))
          _v81 = val2.relative_pose
          _v82 = _v81.pose
          _v83 = _v82.position
          _x = _v83
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v84 = _v82.orientation
          _x = _v84
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
          buff.write(_v81.covariance.tostring())
          _x = val2
          buff.write(_get_struct_2Bd().pack(_x.is_2d_detect, _x.is_yaw_valid, _x.probaility))
          _v85 = val2.local_pose_self
          _v86 = _v85.position
          _x = _v86
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v87 = _v85.orientation
          _x = _v87
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
          _v88 = val2.local_pose_remote
          _v89 = _v88.position
          _x = _v89
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v90 = _v88.orientation
          _x = _v90
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
          _x = val2.dof_4
          buff.write(_get_struct_B().pack(_x))
      _x = self.self_id
      buff.write(_get_struct_i().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.node_frames is None:
        self.node_frames = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.node_frames = []
      for i in range(0, length):
        val1 = swarm_msgs.msg.node_frame()
        _v91 = val1.header
        start = end
        end += 4
        (_v91.seq,) = _get_struct_I().unpack(str[start:end])
        _v92 = _v91.stamp
        _x = _v92
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v91.frame_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v91.frame_id = str[start:end]
        _x = val1
        start = end
        end += 12
        (_x.drone_id, _x.keyframe_id,) = _get_struct_iQ().unpack(str[start:end])
        _v93 = val1.position
        _x = _v93
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v94 = val1.velocity
        _x = _v94
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _x = val1
        start = end
        end += 12
        (_x.yaw, _x.pitch, _x.roll,) = _get_struct_3f().unpack(str[start:end])
        _v95 = val1.quat
        _x = _v95
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        start = end
        end += 1
        (val1.vo_available,) = _get_struct_B().unpack(str[start:end])
        val1.vo_available = bool(val1.vo_available)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.dismap_ids = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sd'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.dismap_dists = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.detected_xyzyaws = []
        for i in range(0, length):
          val2 = swarm_msgs.msg.node_detected_xyzyaw()
          _v96 = val2.header
          start = end
          end += 4
          (_v96.seq,) = _get_struct_I().unpack(str[start:end])
          _v97 = _v96.stamp
          _x = _v97
          start = end
          end += 8
          (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            _v96.frame_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            _v96.frame_id = str[start:end]
          _x = val2
          start = end
          end += 16
          (_x.id, _x.self_drone_id, _x.remote_drone_id,) = _get_struct_q2i().unpack(str[start:end])
          _v98 = val2.dpos
          _x = _v98
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v99 = val2.dpos_std
          _x = _v99
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _x = val2
          start = end
          end += 34
          (_x.dyaw, _x.dyaw_cov, _x.enable_scale, _x.is_yaw_valid, _x.probaility, _x.inv_dep,) = _get_struct_2d2B2d().unpack(str[start:end])
          val2.enable_scale = bool(val2.enable_scale)
          val2.is_yaw_valid = bool(val2.is_yaw_valid)
          _v100 = val2.local_pose_self
          _v101 = _v100.position
          _x = _v101
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v102 = _v100.orientation
          _x = _v102
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          _v103 = val2.local_pose_remote
          _v104 = _v103.position
          _x = _v104
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v105 = _v103.orientation
          _x = _v105
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          _v106 = val2.camera_extrinsic
          _v107 = _v106.position
          _x = _v107
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v108 = _v106.orientation
          _x = _v108
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          val1.detected_xyzyaws.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.detected = []
        for i in range(0, length):
          val2 = swarm_msgs.msg.node_detected()
          _v109 = val2.header
          start = end
          end += 4
          (_v109.seq,) = _get_struct_I().unpack(str[start:end])
          _v110 = _v109.stamp
          _x = _v110
          start = end
          end += 8
          (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            _v109.frame_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            _v109.frame_id = str[start:end]
          _x = val2
          start = end
          end += 16
          (_x.id, _x.self_drone_id, _x.remote_drone_id,) = _get_struct_q2i().unpack(str[start:end])
          _v111 = val2.relative_pose
          _v112 = _v111.pose
          _v113 = _v112.position
          _x = _v113
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v114 = _v112.orientation
          _x = _v114
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          start = end
          end += 288
          _v111.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
          _x = val2
          start = end
          end += 10
          (_x.is_2d_detect, _x.is_yaw_valid, _x.probaility,) = _get_struct_2Bd().unpack(str[start:end])
          val2.is_2d_detect = bool(val2.is_2d_detect)
          val2.is_yaw_valid = bool(val2.is_yaw_valid)
          _v115 = val2.local_pose_self
          _v116 = _v115.position
          _x = _v116
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v117 = _v115.orientation
          _x = _v117
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          _v118 = val2.local_pose_remote
          _v119 = _v118.position
          _x = _v119
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v120 = _v118.orientation
          _x = _v120
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          start = end
          end += 1
          (val2.dof_4,) = _get_struct_B().unpack(str[start:end])
          val2.dof_4 = bool(val2.dof_4)
          val1.detected.append(val2)
        self.node_frames.append(val1)
      start = end
      end += 4
      (self.self_id,) = _get_struct_i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2Bd = None
def _get_struct_2Bd():
    global _struct_2Bd
    if _struct_2Bd is None:
        _struct_2Bd = struct.Struct("<2Bd")
    return _struct_2Bd
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_2d2B2d = None
def _get_struct_2d2B2d():
    global _struct_2d2B2d
    if _struct_2d2B2d is None:
        _struct_2d2B2d = struct.Struct("<2d2B2d")
    return _struct_2d2B2d
_struct_36d = None
def _get_struct_36d():
    global _struct_36d
    if _struct_36d is None:
        _struct_36d = struct.Struct("<36d")
    return _struct_36d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
_struct_iQ = None
def _get_struct_iQ():
    global _struct_iQ
    if _struct_iQ is None:
        _struct_iQ = struct.Struct("<iQ")
    return _struct_iQ
_struct_q2i = None
def _get_struct_q2i():
    global _struct_q2i
    if _struct_q2i is None:
        _struct_q2i = struct.Struct("<q2i")
    return _struct_q2i
