#topic param:
odometry_topic: /quad_0/lidar_slam/odom
cloud_topic: /quad0_pcl_render_node/cloud
global_planning/w_vdir: 1.2
global_planning/w_yawdir: 0.0
global_planning/w_firstnode: 0.2
#viz
view_graph: false
FrontierManager/view_cluster: false
FrontierManager/view_frt: false
# graph
bubble_topo/min_x: 0.8
bubble_topo/min_y: 0.8
bubble_topo/min_z: 0.4
bubble_topo/bubble_min_radius: 0.8
bubble_topo/init_region_size_x: 3.0
bubble_topo/init_region_size_y: 3.0
bubble_topo/init_region_size_z: 2.5
bubble_topo/cube_discrete_size: 0.45
bubble_topo/odom_node_distance: 6.0
bubble_astar/safe_distance: 0.6
# map param
max_update_region_num: 35000
frontier/candidate_dphi: 0.35
frontier/candidate_znum: 2
lidar_perception/fov_up: 45.0
lidar_perception/fov_down: -11.0
lidar_perception/lidar_pitch: 40.0
lidar_perception/fov_viewpoint_up: 40.0
lidar_perception/fov_viewpoint_down: -9.0
lidar_perception/max_ray_length: 16
parallel_astar/update_connection_timeout: 0.008
parallel_astar/insert_node_timeout: 0.008
FrontierManager/cell_size: 0.5
FrontierManager/noise_cell_range: 1
FrontierManager/good_observation_direction_score: 0.7
FrontierManager/good_observation_force_trust_length: 4.0
FrontierManager/good_observation_trust_length: 12.0
FrontierManager/update_length: 10.0 
FrontierManager/cluster_max_size: 6.0
FrontierManager/cluster_min_size: 1.5
FrontierManager/cluster_min_radius: 1.0
FrontierManager/cluster_direction_radius: 0.2
FrontierManager/cluster_minmum_point_num: 4

ViewpointManager/sample_pillar_min_height: 1.2
ViewpointManager/sample_pillar_max_height: 3.0
ViewpointManager/sample_pillar_height_layer_num: 1
ViewpointManager/sample_pillar_min_radius: 2.0
ViewpointManager/sample_pillar_max_radius: 3.5
ViewpointManager/sample_pillar_radius_layer_num: 1
ViewpointManager/sample_pillar_circle_sample_num: 6
ViewpointManager/local_tsp_size: 5
# area
box_num: 1
box_0/down: [-10.0, -6.0, -0.2]
box_0/up: [182.0, 150.2, 380]
dead_area_num: 0
# trajectory param
max_traj_len: 8.0
DilateRadiusSoft: 0.7 # minco threshold
DilateRadiusHard: 0.8 # collision check threshold
MaxCorridorSize: 3.5
MaxVelMag: 3.0
maxBdrMag: 6000.0
MaxTiltAngle: 0.4
MinThrust: 15.0
MaxThrust: 20.0
VehicleMass: 1.9
GravAcc: 9.8
HorizDrag: 0.70
VertDrag: 0.80
ParasDrag: 0.01
SpeedEps: 0.0001
WeightT: 1500.0
WeightSafeT: 300.0
# [pos_weight, vel_weight, omg_weight, theta_weight, thrust_weight]
ChiVec: [1.5e+5, 1.0e+4, 8.0e+3, 8.0e+4, 8.0e+4]
SmoothingEps: 0.02
IntegralIntervs: 32
RelCostTol: 5.0e-6
#param for yaw opt
yaw_max_vel: 3.0
yaw_rho_vis: 8000.0
yaw_time_fwd: 2.0
